### ISSUE TITLE
Correct Answer is displayed as NA

### ISSUE THREAD

**Issue by sidneydemoraes** [QuizandSurveyMaster/quiz_master_next#1018]
## Site Info
WordPress Version: 5.4.2
QSM Version:  7.0.1
Browser: Any

## General description
Using `%QUESTIONS_ANSWERS%` on my Results Page shows correctly the question, the provided answer but never shows the correct answer. It just shows `NA`.
![image](https://user-images.githubusercontent.com/696278/89832785-36a94000-db36-11ea-9674-5ee89402ecdb.png)

I have assigned points to the correct answers but it makes no difference
![image](https://user-images.githubusercontent.com/696278/89832868-622c2a80-db36-11ea-8e1c-cd01c709fbe5.png)

## Expected behavior
QSM should show the appropriate correct answer on the results page.

## Actual behavior
The correct answer is always just `NA`.

## Steps to reproduce the behavior
N/A

**Comment by talent74** [comment]
I have the same issue. The correct answer being returned as NA for some questions.

I could be wrong, but it might be related to missing entities. Like using apostrophes (') or accents (å, î).

Can you please confirm, deny or at least provide a fix.

**Comment by talent74** [comment]
@sidneydemoraes

Are you using the "points" system? I was too and had no issue with it until the last few updates of the plugin.

It appears the points system now causes problems. I was told to fix it by using the "correct/incorrect" system or "both".

Hopefully they will fix the points system soonest.

**Comment by diksha825** [comment]
Hi @talent74 

In Points - Grading System, there is no correct or wrong answer, therefore results page will only show you user selected answer.

You need to use "Both" for Grading System, so that you can assign point to an answer and check it as the correct answer. This way, it will show you the correct answer in your results page.

QSM Team

**Comment by zubairraeen** [comment]
Hello,
I have tested this issue with the latest version of QSM, and it is now resolved and functioning correctly. Therefore, I am closing this task.

Thank you!
