### ISSUE TITLE
Start time and end time option with start date and end date?

### ISSUE THREAD

**Issue by jasimp** [QuizandSurveyMaster/quiz_master_next#1027]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.4
QSM Version: 7.0.1
Browser: all

## General description
If this is a bug, give a general description of what you are experiencing. If this is a feature request, include what the feature is that you are requesting.

Link to quiz or screenshot (if relevant): 

![image](https://user-images.githubusercontent.com/7235269/90112979-be26c700-dd61-11ea-90c8-c94b13e04ad2.png)

## Feature request

Is there any option for Start time and end time option with start date and end date? for Eg; if we are conducting an exam with start and end time restriction, than means if the student joined the exam late, the exam should close in the proper end time. how we can implement with this plug in?

**Comment by etvarun** [comment]
Hi @jasimp 

Currently we don't have this feature in QSM, 

We have recorded this feature request and will consider implementing in a future release.

Thanks & Regards,
Varun Kumar

**Comment by jasimp** [comment]
Thanks a lot for the prompt reply
It will be better if we can add timer for each question too. if the student didn't answer the question within the time limit, then the system will move to next question.

**Comment by etvarun** [comment]
This option is already available in our Advanced Timer addon. Once you install and activate that addon, you will get an option to set the timer per page. You can have one or more question on the page depending on the requirements.

**Comment by jasimp** [comment]
Thank you for your response
I think i have to give clarify more for best understanding. I was looking for a entry time and exit time, not timer for every page.
Example: if we set the open and ending date and time for a specific quiz ( start: 20/08/2020 @ 10:00AM , End : 20/08/2020 12:00PM), then the quiz can open / access while reaching that date and time. Also quiz need to quit the configured end time similar to timer. this will avoid early and late access  to the quiz

**Comment by etvarun** [comment]
Hi @jasimp 

We have added the option to set start and end time along with dates in latest version of QSM.

From your last comment, it appears you might need more customization. Our colleagues at [Justhyre](https://justhyre.com/) can help you with that. You can [Get a quote from Justhyre](https://justhyre.com/get-a-quote/) for any custom work related to QSM

Regards,
Varun
