### ISSUE TITLE
mandatory field getting inactivated while editing the questions

### ISSUE THREAD

**Issue by jasimp** [QuizandSurveyMaster/quiz_master_next#1033]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.4
QSM Version: 7.0.1
Browser: all

## General description
Mandatory field getting inactivated while click on the editing button of the the question. It should stay same as the correct answer section field.

Link to quiz or screenshot (if relevant): 
![image](https://user-images.githubusercontent.com/7235269/90332123-52e02d80-dfcb-11ea-85fe-2ae9818d1b24.png)
![image](https://user-images.githubusercontent.com/7235269/90332099-29bf9d00-dfcb-11ea-9fbe-f422e1d3dde1.png)

## Expected behavior
Mandatory field getting inactivated while click on the editing button of the the question. It should stay same as the correct answer section field and should not be changed unless the user un tick that option

## Actual behavior
Mandatory field getting inactivated while click on the editing button of the the question. It should stay same as the correct answer section field and should not be changed unless the user un tick that option

## Steps to reproduce the behavior
Now we need to re tick the mandatory tick box again if we click the edit button

**Comment by etvarun** [comment]
This has been fixed in QSM version 7.0.2
