### ISSUE TITLE
Question number not showing on result page or result email

### ISSUE THREAD

**Issue by jasimp** [QuizandSurveyMaster/quiz_master_next#1108]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.4
QSM Version: 7.0.2
Browser: all

## General description
Question number not showing on result page or result email even its enabled. its only showing on front end quiz page

## Expected behavior
If Question number enabled, its should show with all questions and very where. 

## Actual behavior
Question number not showing on result page or result email even its enabled. its only showing on front end quiz page
## Steps to reproduce the behavior
enable a question number in the option and submit a quiz. the question number is not there on the result page or result email.

**Comment by zubairraeen** [comment]
Hello,
I have tested this issue with the latest version of QSM, and it is now resolved and functioning correctly. Therefore, I am closing this task.

Thank you!
