### ISSUE TITLE
Option for quiz answer scoring

### ISSUE THREAD

**Issue by jasimp** [QuizandSurveyMaster/quiz_master_next#1109]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

## Site Info
WordPress Version: 5.4
QSM Version: 7.0.1
Browser: all

## General description
Looking for an option for quiz answer scoring. for example there is a 10 question quiz and 20 participants. we want to know which question got more correct answers and less..less

## Feature request
Looking for an option for quiz answer scoring. for example there is a 10 question quiz and 20 participants. we want to know which question got more correct answers and lowest second quest and lowest third question etc... correct answer ranking

**Comment by pranav-et** [comment]
Hi @jasimp,
You can achieve the described functionality with our Reporting and Analysis Add-on. Visit this [link](https://quizandsurveymaster.com/downloads/results-analysis/) to learn more and download the add-on
Thanks
