### ISSUE TITLE
Safety feature needed: Option to store the selected answer either local PC or database

### ISSUE THREAD

**Issue by jasimp** [QuizandSurveyMaster/quiz_master_next#1110]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.4
QSM Version: 7.0.2
Browser: all

## General description
Facing issue if the any unexpected network disconnection or PC shutdown  happened during a quiz especially a quiz has hundreds of questions and if this happening during the submission or just before that and  all the entered answers are get lost! Is there any solution to save the answers automatically on database or local machine while one question answered and moving to next. This can help to retrieve the already completed quiz answers if the participant re open the browser or re start the same quiz.if this function is not there looking for the same. Other wise the quiz only beneficial for small quiz intakes or just for survey or form submission.

## Expected behavior
Facing issue if the any unexpected network disconnection or PC shutdown  happened during a quiz especially a quiz has hundreds of questions and if this happening during the submission or just before that and  all the entered answers are get lost! Is there any solution to save the answers automatically on database or local machine while one question answered and moving to next. This can help to retrieve the already completed quiz answers if the participant re open the browser or re start the same quiz.if this function is not there looking for the same. Other wise the quiz only beneficial for small quiz intakes or just for survey or form submission.

## Actual behavior
There is no answer saving safety feature currently which is causing loosing on all answers if any unexpected network/ browser/ PC interruption happens.

## Feature request
Safety feature needed: Option to store the selected answer either local PC or database

**Comment by pranav-et** [comment]
Hi @jasimp ,
You can achieve the described functionality with our Save and Resume Add-on. Visit this [link](https://quizandsurveymaster.com/downloads/save-and-resume/) to learn more and download the add-on.
Thanks
