### ISSUE TITLE
URL Parameters not working when no Contact fields added.

### ISSUE THREAD

**Issue by sadortun** [QuizandSurveyMaster/quiz_master_next#1121]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version:  latest
QSM Version:  latest
Browser: chrome

## General description
`qsm_contact_fields_end` hook not getting called when no contact fields are already present. This have for effect that `URL Parameters` are not working

## Expected behavior
URL Parametres should be independent of contact fields

## Actual behavior
No contact fields = URL Parameters not working

## Steps to reproduce the behavior
Create a survey without contact fields, and add URL Parameters.

**Comment by etvarun** [comment]
This has been fixed in latest version of the addon and core.
