### ISSUE TITLE
DivisionByZeroError when opening a quiz random questions set and questions per page set to 0

### ISSUE THREAD

**Issue by lukasan** [QuizandSurveyMaster/quiz_master_next#1156]
## Site Info
WordPress Version: 5.5.1
QSM Version: 7.1.5
Browser: Firefox

## General description
I've encountered a DivisionByZeroError on production. I copied the whole site to a local instance for debugging.
Bug:
`Fatal error: Uncaught DivisionByZeroError: Modulo by zero in E:\xampp\htdocs\wordpress\wp-content\plugins\quiz-master-next\php\classes\class-qmn-quiz-manager.php:913 Stack trace: #0 E:\xampp\htdocs\wordpress\wp-content\plugins\quiz-master-next\php\classes\class-qmn-quiz-manager.php(607): QMNQuizManager->display_questions(Object(stdClass), Array, Array) #1 E:\xampp\htdocs\wordpress\wp-content\plugins\quiz-master-next\php\classes\class-qmn-quiz-manager.php(331): QMNQuizManager->display_quiz(Object(stdClass), Array, 0) #2 E:\xampp\htdocs\wordpress\wp-includes\shortcodes.php(343): QMNQuizManager->display_shortcode(Array, '', 'mlw_quizmaster') #3 [internal function]: do_shortcode_tag(Array) #4 E:\xampp\htdocs\wordpress\wp-includes\shortcodes.php(218): preg_replace_callback('/\\[(\\[?)(mlw_qu...', 'do_shortcode_ta...', '[mlw_quizmaster...') #5 E:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(287): do_shortcode('[mlw_quizmaster...') #6 E:\xampp\htdocs\wordpress\wp-includes\plugin.php(206): WP_Hook->apply_filters('[mlw_qui in E:\xampp\htdocs\wordpress\wp-content\plugins\quiz-master-next\php\classes\class-qmn-quiz-manager.php on line 913`

## Expected behavior
List quiz questions randomly.

## Actual behavior
Opening the quiz gives DivisionByZeroError

## Steps to reproduce the behavior

1. Create a timed quiz.
2. Get any amount of questions. 
3. Set max questions less or equal to the amount of questions. Page amount doesn't matter.
4. **Set questions per page to be default 0**
5. **Set random questions to random questions**

I think that random questions function somewhere takes the questions per page value and divides that. No idea, though.
If random questions is set to disabled, then the error doesn't appear and the quiz works.
If random questions is not set to disabled, but questions per page is not 0, then the error also doesn't appear and the quiz works.

**Comment by etvarun** [comment]
Hi @lukasan 

Thank you for reporting this. We are looking into it and will provide an update soon.

**Comment by lukasan** [comment]
I can confirm this is an isolated to 7.1.5 version
I was originally upgrading to latest from 6.4.12. Tried all in-between versions and some combinations of upgrading/downgrading. Everytime only 7.1.5 breaks.
