### ISSUE TITLE
request : type math with wiris library

### ISSUE THREAD

**Issue by hatami1372** [QuizandSurveyMaster/quiz_master_next#1201]
## Site Info
WordPress Version: 5.6
QSM Version: 7.1.9
Browser: Edge 87

I need a equation button in default QSM editor(tiny mce) like [Equation Editor ](https://wordpress.org/plugins/equation-editor/) to type latex formula
but after i install this plugin , Equation buttons not showing in the QSM TinyMCE Editor .
Please Add Equation editor to QSM or help me to add this plugin to QSM TinyMCE editor
thanks

**Comment by zubairraeen** [comment]
This plugin has been closed as of June 19, 2022, and is not available for download.
