### ISSUE TITLE
It would be nice to have an option where you choose not to show first and last screens of quiz

### ISSUE THREAD

**Issue by krilim** [QuizandSurveyMaster/quiz_master_next#1205]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.6
QSM Version: 7.19
Browser: any

## Feature request
It would be nice to have an option where you choose not to show first and last screens of quiz

**Comment by diksha825** [comment]
Hi @krilim 

We have forwarded this feature request to our development team.Thanks for your feedback.
 
QSM Team

**Comment by diksha825** [comment]
Hi @krilim 

We are pleased to inform you that we have implemented your feature request in QSM 7.3.8. Please update to latest version.

**Comment by pranav-et** [comment]
Customer notified
