### ISSUE TITLE
%QUESTIONS_ANSWERS% not displaying correctly

### ISSUE THREAD

**Issue by awharton2** [QuizandSurveyMaster/quiz_master_next#1264]
## Site Info
WordPress Version: 5.6.2
QSM Version: 7.1.12
Browser: Safari 14.0.3, Chrome 88.0.4324.192
All plugins deactivated to rule out a cause by another plugin. 

## General description

When displaying results using %QUESTIONS_ANSWERS%, questions with a rich text answer do not show an incorrectly selected answer.  The score is calculated correctly, but only shows the correct answer in green.  See screenshot.

When using %QUESTIONS_ANSWERS_EMAIL%, the behavior works as expected.

Link to quiz or screenshot (if relevant): https://imgur.com/9gmZdTn

## Expected behavior
Expect the wrong answer to have a red X bullet with red text instead of a green circle bullet with green text color.

## Actual behavior
The correct answer is highlighted in green with a green bullet with no changes to the incorrect answer.

## Steps to reproduce the behavior
- Create a Vertical Multiple Choice question
- Select Rich Answers
- Complete quiz with an incorrect answer and Submit

**Comment by etvarun** [comment]
Hello @awharton2,

Thank you for reporting this issue. Our team will look into this and provide a resolution in an upcoming release.

**Comment by etaditya** [comment]
Please update to 7.1.13
If the issue persists please update
