### ISSUE TITLE
SQL Syntax Error

### ISSUE THREAD

**Issue by dhurlburtusa** [QuizandSurveyMaster/quiz_master_next#1283]
## Site Info

WordPress Version: 5.7
QSM Version: 7.1.4
Browser: Not relevant to this issue but using Chrome Version 86.0.4240.198 (Official Build) (64-bit)

## General description

The commit https://github.com/QuizandSurveyMaster/quiz_master_next/commit/8c5f925afb8f4279506bb28dad7e57a6d1708aab#diff-780dc4b339602928ee391f3b78daf7b13a23fc7cb1753c77c050458a2b48a395 broke the query to load the quiz's questions. It inserts `{` and `}` in the SQL. The edit on line 483 forgot to remove these characters. Now MySQL complains with:

```
[26-Mar-2021 01:34:55 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{ } {  } {ORDER BY question_order ASC} {    }' at line 1 for query SELECT * FROM wp_qyxhycyyyb_mlw_questions WHERE quiz_id=10 AND deleted=0 { } {  } {ORDER BY question_order ASC} {    } made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), ...
```

Note: This is in the older, deprecated code. I haven't yet figured out how to get the quizzes to load with the non-deprecated code. I'll do some research after submitting this issue. I assume I'll need to re-create the quizzes.

## Expected behavior

Load the questions for the quiz.

## Actual behavior

Quiz page loads but with no questions.

## Steps to reproduce the behavior

Open any page with a quiz.

## Feature request

Add functional tests to the codebase to prevent regressions or require that changes are tested.

**Comment by etaditya** [comment]
> ## Site Info
> WordPress Version: 5.7
> QSM Version:
> Browser: Not relevant to this issue but using Chrome Version 86.0.4240.198 (Official Build) (64-bit)
> 
> ## General description
> The commit [8c5f925#diff-780dc4b339602928ee391f3b78daf7b13a23fc7cb1753c77c050458a2b48a395](https://github.com/QuizandSurveyMaster/quiz_master_next/commit/8c5f925afb8f4279506bb28dad7e57a6d1708aab#diff-780dc4b339602928ee391f3b78daf7b13a23fc7cb1753c77c050458a2b48a395) broke the query to load the quiz's questions. It inserts `{` and `}` in the SQL. The edit on line 483 forgot to remove these characters. Now MySQL complains with:
> 
> ```
> [26-Mar-2021 01:34:55 UTC] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{ } {  } {ORDER BY question_order ASC} {    }' at line 1 for query SELECT * FROM wp_qyxhycyyyb_mlw_questions WHERE quiz_id=10 AND deleted=0 { } {  } {ORDER BY question_order ASC} {    } made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), ...
> ```
> 
> Note: This is in the older, deprecated code. I haven't yet figured out how to get the quizzes to load with the non-deprecated code. I'll do some research after submitting this issue. I assume I'll need to re-create the quizzes.
> 
> ## Expected behavior
> Load the questions for the quiz.
> 
> ## Actual behavior
> Quiz page loads but with no questions.
> 
> ## Steps to reproduce the behavior
> Open any page with a quiz.
> 
> ## Feature request
> Add functional tests to the codebase to prevent regressions or require that changes are tested.

**Comment by etaditya** [comment]
Thanx for informing about this issue.
Could you please update the version of QSM in which you could replicate this issue.

**Comment by etaditya** [comment]
Thanx for your contribution regarding this issue.

It would be really great if you could answer few questions:
What is the initial version of QSM you have installed? (You can find this information from Help page in QSM Menu)
Are you facing this issue with the older quizzes and newly created quizzes are working fine?
Could you see the questions in edit quiz page (in backend) but they are not appearing in frontend?

Note: Simple fix for this is, Just re-save any question in edit quiz page in the quiz you are facing the issue?
Let me know if this works for you.

**Comment by dhurlburtusa** [comment]
> What is the initial version of QSM you have installed? (You can find this information from Help page in QSM Menu)

Initial Version : 4.7.5
Current Version : 7.1.14

> Are you facing this issue with the older quizzes and newly created quizzes are working fine?

Just older quizzes afaik. I didn't try to create new quizzes. All quizzes are about 3 or more years old.

> Could you see the questions in edit quiz page (in backend) but they are not appearing in frontend?

They were not showing up on the backend or the frontend.

> Note: Simple fix for this is, Just re-save any question in edit quiz page in the quiz you are facing the issue?

I have updated all (well all the ones I display to users) by adjusting something in the Styles tab. But I had already put in the fix I put in the PR. So, I don't know that the side-effect of updating the quizzes was.

**Comment by etaditya** [comment]
Thanks for information.

For now i consider this issue as resolved and Incase you face any issue with our plugin please feel free to contact us.
