### ISSUE TITLE
Images as answers

### ISSUE THREAD

**Issue by OC2PS** [QuizandSurveyMaster/quiz_master_next#146]
Answer fields allow HTML.

But would be nice if admin could set images from media gallery as options.

The quiz taker should be able to select the option by clicking on the picture as well as by clicking on the radio button/ checkbox. 

Would be useful for #19 too

**Comment by fpcorso** [comment]
Indeed. I am planning on converting the question textarea to the wordpress editor soon and I will try different solutions to  allow adding media to the answers to.

**Comment by fpcorso** [comment]
Another user has requested this feature. Bumping priority from very low to low.

**Comment by vikasprogrammer** [comment]
This issue is now implemented as part of the master branch in 6.3.0 release.
