### ISSUE TITLE
Replies appear randomly in emails

### ISSUE THREAD

**Issue by opalestrinha** [QuizandSurveyMaster/quiz_master_next#1464]
Hi!

We noticed that after the last update to version 7.3.2 the responses sent by email are being displayed randomly.

The answers don't come in ascending order but randomly.

I would like to know how to disable this function or fix this bug

**Comment by etvarun** [comment]
Hi @opalestrinha 

We will look into this and get back to you asap. 

Regards,
Varun

**Comment by opalestrinha** [comment]
> Oi @opalestrinha
> 
> Vamos dar uma olhada nisso e voltar para você o mais rápido possível.
> 
> Cumprimentos,
> Varun

Thanks.

I will be running a test on 09/20/2021 and will use the QMS plugin.

Would you be able to help me resolve this issue before that date?

Send me your email so I can add it to a test test so I can receive and check how emails are arriving.

**Comment by diksha825** [comment]
Hi @opalestrinha

Could you submit a ticket on https://quizandsurveymaster.com/contact-support/ along with quiz link and wp admin details. I willl make sure that issue is fixed asap.

Team QSM

**Comment by diksha825** [comment]
Just to inform you, our team doesnt work on weekends, so the sooner you submit details, the sooner you would get help.

**Comment by opalestrinha** [comment]
Hi

We have already contacted you via email and we have not been able to resolve this issue yet.

Whenever I send my website login data, they inform me that they cannot access it.

Are there any other faster ways we can communicate to resolve this issue? Skype, Whatsapp, Facebook, or other means?

I sent a message to support on 06/09/2021 and to this day my problem has not been resolved.

**Comment by diksha825** [comment]
Appologies for that. Please send a mail along with details to diksha@expresstech.io . I will take it up personally.

**Comment by opalestrinha** [comment]
Thank you very much for the support.

I will now send the email with the information

**Comment by opalestrinha** [comment]
The email has already been sent.

Thanks.
