### ISSUE TITLE
Characters replacing

### ISSUE THREAD

**Issue by cedrick-f** [QuizandSurveyMaster/quiz_master_next#1476]
Hi!

There are several character replacement procedures during the editing/re-editing of questions. As a result, some questions do not display as expected.
For example  :

```
<pre class="EnlighterJSRAW" data-enlighter-language="python">
class Stylo:
    def __init__(self, c = "bleu"):
        self.coul = c
    def couleur(self): 
        return self.coul
</pre>
```

appears like that :

![image](https://user-images.githubusercontent.com/11462584/134801930-0b676455-5882-45fc-898a-47be0ac403e6.png)

Using `pre` tag without any plugin gives :

```
<pre>
class Stylo:
    def __init__(self, c = "bleu"):
        self.coul = c
    def couleur(self): 
        return self.coul
</pre>
```

![image](https://user-images.githubusercontent.com/11462584/134802419-81558ef9-3048-40ef-a810-14bf6d95f4a4.png)

A workaround is to use XML encoding :
```
<pre>
class Stylo:&#10;&#13;
    def __init__(self, c = "bleu"):&#10;&#13;
        self.coul = c&#10;&#13;
    def couleur(self): &#10;&#13;
        return self.coul&#10;&#13;
</pre>
```

But these characters are replaced again when the question is re-edited!

## Site Info
WordPress Version: 5.8.1
QSM Version: 7.3.2
Browser: FF

Thank you by advance for your help

**Comment by etvarun** [comment]
Hi @cedrick-f 

Thank you for posting your issue. 

However, we need a bit more info in order to understand this issue clearly.

Kindly provide us more details on what you are trying to achieve, and let us know the steps to replicate this issue?

Please mention if you are using any third party plugins.

If possible please share your staging URL with us so that we can inspect it live. 

Looking forward to your response.

Regards,
Varun

**Comment by cedrick-f** [comment]
Hi

Here is a link to an example : [https://info.blaisepascal.fr/quiz/test-2](url)
And here is what i exactly entered in the question editor:
![image](https://user-images.githubusercontent.com/11462584/134901594-50db0a6c-83b3-4bd8-a65c-5fadbfcc7bce.png)

If i change the tab (Option for example) and re-open the question editor, i can see this :
![image](https://user-images.githubusercontent.com/11462584/134901889-80c90cac-2746-4023-8739-676c3a234424.png)

This is not the only issue, but can you reproduce it ?


Regards

**Comment by etvarun** [comment]
@cedrick-f 

Thank you very much for explaining the issue. 

Our team will look into this and keep you posted here.

**Comment by zubairraeen** [comment]
Hi @cedrick-f,
Thank you very much for your patience.
Our team worked on it actually for some security reasons question description values are trimming before saving in the database but for solving this issue our team has added a filter in our latest QSM plugin version 7.3.3 please update the plugin and use this hook in your current theme `functions.php` file
```
// Disable trim
add_filter( 'qsm_trim_question_description', '__return_false' );
```

Thanks

**Comment by cedrick-f** [comment]
Thank you very much !
