### ISSUE TITLE
Bug - Import doesn't work

### ISSUE THREAD

**Issue by Aldmors** [QuizandSurveyMaster/quiz_master_next#1674]
## Site Info
WordPress Version: Version: 5.8.2
QSM Version:  7.3.7
PHP : 8.0.14

## General description

when importing QSM data to a new page. After importing the data, despite the correct import (when you try again, you get a message that the quizzes already exist)
they do not appear in the quizzes in the plug-in menu, it is not possible to manage them and they do not work on the website

## Steps to reproduce the behavior
Use Wordpress Import
Import date to new page

**Comment by akshay-jh** [comment]
Thanks for the reaching out to us.

WordPress Import is not sufficient to import QSM data. You can use our [Export & Import Addon](https://quizandsurveymaster.com/downloads/export-import/) to import your whole QSM data.
