### ISSUE TITLE
Facebook and Twitter button text

### ISSUE THREAD

**Issue by OC2PS** [QuizandSurveyMaster/quiz_master_next#172]
QMN should ask the text for Facebook and Twitter buttons. e.g. I might want to say the wordy "Share my results on Facebook", someone else may say "Tell friends on Facebook, and yet another may just say "Facebook"

**Comment by fpcorso** [comment]
Ah, hadn't thought of that. I can see that being something used if implemented.

**Comment by OC2PS** [comment]
Sad to see this go stale. Would like to see some progress on this.
