### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by Aldmors** [QuizandSurveyMaster/quiz_master_next#1742]
## Site Info
WordPress Version:  5.9
QSM Version: 7.3.10
PHP Version: 8.0.14
MySQL Version: 5.5.5

## General description
When I try to create a quiz, it crashes a fatal error. 

This started happening after the last update
Rollback fix this.
##
Fatal error: Uncaught TypeError: array_replace(): Argument #1 ($array) must be of type array, bool given in .../domains/test.glospokolenia.pl/public_html/wp-content/plugins/quiz-master-next/php/admin/admin-dashboard.php:624
 Stack trace: #0 ..../domains/test.glospokolenia.pl/public_html/wp-content/plugins/quiz-master-next/php/admin/admin-dashboard.php(624): array_replace(false, Array) 
#1 .../domains/test.glospokolenia.pl/public_html/wp-includes/class-wp-hook.php(307): qsm_create_new_quiz_from_wizard('')
 #2 .../domains/test.glospokolenia.pl/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) 
#3 /home/kaila/domains/test.glospokolenia.pl/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
 #4 /home/kaila/domains/test.glospokolenia.pl/public_html/wp-admin/admin.php(175): do_action('admin_init')
 #5 {main} thrown in /home/kaila/domains/test.glospokolenia.pl/public_html/wp-content/plugins/quiz-master-next/php/admin/admin-dashboard.php on line 624

**Comment by akshay-jh** [comment]
Hi [Jakub Biernat](https://github.com/Aldmors),

Thank you for reporting this issue. We are able to replicate the same on our side.

This has been fixed in  [#1745](https://github.com/QuizandSurveyMaster/quiz_master_next/pull/1745) and will be included in next version release.
