### ISSUE TITLE
5 small propose

### ISSUE THREAD

**Issue by Aldmors** [QuizandSurveyMaster/quiz_master_next#1743]
## Feature request
I have, 5 small thinks to propose:
1. Add an option in the settings to set the default number of answers, thanks to this.
 We will not have to on each question e.g  4 click to create answers.
2. Add numbering of questions to the quiz menu and also to the answer results. This will make it easier to navigate the quiz menu. It will also improve navigation through the answer forms when, for example, questions are in random order
3. Add an optional separate page for adding questions, where you can save with the click of a button and proceed to creating a new question.
4. Add, checking if the correct answer was marked in the created question. In case of a potential mistake and no answer is selected, there is a lot of searching, e.g. with 50 questions
5.  Add the ability to import questions from e.g. csv files

**Comment by etvarun** [comment]
Hi @Aldmors 

Thank you for sharing these suggestions. These are all really good points.

We will evaluate these further and plan for future releases accordingly.

**Comment by akshay-jh** [comment]
Hi @Aldmors 

We have added option to set the default number of answers in QSM 7.3.14.

Thank you for your suggestions. Also we will evaluate and plan other remaining points for future releases.
