### ISSUE TITLE
QSM don't create a new quiz

### ISSUE THREAD

**Issue by gilbertwojaczekkubica** [QuizandSurveyMaster/quiz_master_next#1759]
## Site Info
WordPress Version: 5.9
QSM Version: 7.3.10
Browser: Safari 15.3

## General description
Bug/error. When I create a new quiz/survet I see a critical error 
`Błąd typu E_ERROR został spowodowany w linii 624 pliku /home/srv41565/domains/hiszpanskiprzykawie.pl/public_html/wp-content/plugins/quiz-master-next/php/admin/admin-dashboard.php. Komunikat błędu: Uncaught TypeError: array_replace(): Argument #1 ($array) must be of type array, bool given in /home/srv41565/domains/hiszpanskiprzykawie.pl/public_html/wp-content/plugins/quiz-master-next/php/admin/admin-dashboard.php:624
Stack trace:
#0 /home/srv41565/domains/hiszpanskiprzykawie.pl/public_html/wp-content/plugins/quiz-master-next/php/admin/admin-dashboard.php(624): array_replace(false, Array)
#1 /home/srv41565/domains/hiszpanskiprzykawie.pl/public_html/wp-includes/class-wp-hook.php(307): qsm_create_new_quiz_from_wizard('')
#2 /home/srv41565/domains/hiszpanskiprzykawie.pl/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 /home/srv41565/domains/hiszpanskiprzykawie.pl/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#4 /home/srv41565/domains/hiszpanskiprzykawie.pl/public_html/wp-admin/admin.php(175): do_action('admin_init')
#5 {main}
  thrown
`

Link to quiz or screenshot (if relevant): none

## Expected behavior
Repair

## Actual behavior
I can't create a quiz

**Comment by akshay-jh** [comment]
Hi [gilbertwojaczekkubica](https://github.com/gilbertwojaczekkubica),

Thank you for reporting this issue. We have fixed this issue in latest version of QSM 7.3.11. 

Please let us know if you face any further issues.
