### ISSUE TITLE
Fix block.js - constants

### ISSUE THREAD

**Issue by MarcoHaase** [QuizandSurveyMaster/quiz_master_next#1945]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 6.0.1
QSM Version: 8.0.3
Browser: Chrome

## General description
javascript errors: TextControl, SelectControl, InspectorControls already set while using block.js

## Expected behavior
no error message javascript will work

## Actual behavior
error message javascript dont work

## Steps to reproduce the behavior
create custom gutenberg block with global TextControl variable. run quiz

## Feature request
scope function like this:

```
(function (blocks, blockEditor, components) {
    var el = wp.element.createElement;
    const { registerBlockType } = blocks;
    const { InspectorControls } = blockEditor;
    const { TextControl, SelectControl, ServerSideRender } = components;

    /*
     * Registers the main QSM block
     */
...
})(window.wp.blocks, window.wp.blockEditor, window.wp.components);
```

**Comment by etvarun** [comment]
This issue has been fixed in QSM 8.0.7
