### ISSUE TITLE
Some symbols should not be replaced in `<pre>` tags.

### ISSUE THREAD

**Issue by cedrick-f** [QuizandSurveyMaster/quiz_master_next#1951]
Hi,

## Site Info
WordPress Version: 5.9.3
QSM Version: 8.0.3
Browser: Firefox 103.0.2

## General description
Some symbols  placed in `<pre>` tag, are replaced in question description after editing back the question.

## Expected behavior
Keep theses symbols unchanged in `<pre>` tags.

## Actual behavior
Some symbols (`<`, `>`, `[`, `]`, ... for example) placed in `<pre>` tag, are replaced in question description after editing back the question ... and don't appear in quiz view.

## Steps to reproduce the behavior
Create a new question
Insert `<pre>a<b</pre>` in the description (Text mode)
Save Question
Edit another question or go to another tab.
Edit back the question (in Text mode)

==> `<pre>a&lt;b</pre>`

Thanks by advance !

**Comment by zubairraeen** [comment]
When placed within the "pre" tag, HTML will be displayed as raw HTML tags without any formatting.
