### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Aldmors** [QuizandSurveyMaster/quiz_master_next#2068]
Please provide the following information when creating your issues:

## Site Info
WordPress Version: 6.1.1
QSM Version: 8.0.8
Browser: 

## General description
JS error when Disable auto fill for Quiz input is selected, which prevents the quiz from being start
When 2 people enter questions to one person, the questions will not be saved
Link to quiz or screenshot (if relevant): 
Niespodziewanie (losowo) zablokowało się dodawanie nowych pytań

**Comment by zubairraeen** [comment]
This issue is already fixed in our latest released code
closing it
