### ISSUE TITLE
all questions is not show in post page 

### ISSUE THREAD

**Issue by saibal25** [QuizandSurveyMaster/quiz_master_next#2098]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues: all questions is not show in post page , i this plugin i write 30 questions but only show 11 question in post page. 

## Site Info
WordPress Version: [6.1.1 version.]
QSM Version: 8.0.10
Browser: chrome

## General description
If this is a bug, give a general description of what you are experiencing. If this is a feature request, include what the feature is that you are requesting.

Link to quiz or screenshot (if relevant): 

## Expected behavior
If you are reporting a bug, please describe what you are expecting the plugin to do. If this is a feature request, delete this section.

## Actual behavior
If you are reporting a bug, please describe what you are experiencing. If this is a feature request, delete this section.

## Steps to reproduce the behavior
If you are reporting a bug, describe the exact steps you are taking that results in the behavior described above. If this is a feature request, delete this section.

## Feature request
If you are reporting a bug, delete this section. If you are requesting a feature, please explain what you would like to have in the plugin. Please include examples of other systems/software that may have similar features as well as the exact way you would use this feature.

**Comment by zubairraeen** [comment]
please provide more information
