### ISSUE TITLE
Saving quiz answers locally

### ISSUE THREAD

**Issue by gamekid88** [QuizandSurveyMaster/quiz_master_next#210]
Users want to be able to save there answers locally so that in case of a power outage or connection lost their answers will not be lost.

**Comment by nipasarker01** [comment]
Hi..is it working?

Can user save the questions and come back and finish the quiz later.?

**Comment by fpcorso** [comment]
Hey @nipasarker01 !

No, this issue is still open as this feature has not been created yet for this plugin. It is currently being researched to **potentially** be added in 6.1.0 which will not be released for a couple of months.
