### ISSUE TITLE
Separate point totals for different catagories

### ISSUE THREAD

**Issue by gamekid88** [QuizandSurveyMaster/quiz_master_next#213]
Users want to be able to assign points to different categories based on the answers selected. Then they want to be able to show separate total points for each category.

**Comment by ChristlLang** [comment]
Would be great

**Comment by fpcorso** [comment]
I have had another request for this.

**Comment by sriordan9** [comment]
Another (similar) request has been made for this. More specifically to filter questions by category on the Reporting and Analysis addon.
