### ISSUE TITLE
Blank screen instead of survey results after hitting "submit" button

### ISSUE THREAD

**Issue by barzoj** [QuizandSurveyMaster/quiz_master_next#2131]
## Site Info
WordPress Version: 6.1.1
QSM Version: 8.1.1
Browser: Chrome 110.0.5481.96 

## Expected behavior
quiz result displayed

## Actual behavior
blank page 

## Steps to reproduce the behavior
trivial, in our case every quiz shows blank page in place of results since 8.0

**Comment by zubairraeen** [comment]
Hi are you still facing same issue

**Comment by zubairraeen** [comment]
I did not encounter any issues in QSM version 8.1.1 or the latest version. The results are displaying as expected.

Thank you
