### ISSUE TITLE
Notify user as time is almost out

### ISSUE THREAD

**Issue by gamekid88** [QuizandSurveyMaster/quiz_master_next#217]
Users want a pop up to show when the quiz timer expires. This would also be useful when the timer is getting close to 0 to warn the quiz user that the time is almost up.

**Comment by fpcorso** [comment]
@gamekid88 Can you provide another example of what the user wants? Do they just want a small dialog to appear warning the user or more like a notification to appear somewhere?

**Comment by gamekid88** [comment]
I think they want the ability for a small dialog with a message. Maybe as it approaches 0 there will be a little notification on the right side under the timer and once it gets in the last 30 seconds a dialog will appear in the middle warning them that the quiz will end soon.

**Comment by fpcorso** [comment]
What if the timer itself flashed or changed colors at different intervals? Would that work for what your user was describing or did they specifically want the notification and popup?

**Comment by gamekid88** [comment]
They didn't specify only a pop up of some sort. But the changing color of the timer might be a simpler fix. I don't know how many people are going to want a pop up disturbing them during their test. Maybe green, yellow, red. Maybe have an algorithm in place so it calculates a point to change color based on the amount of time the admin has allotted for the test.
