### ISSUE TITLE
Quizzes & Surveys section should list only currently logged in author's quizzes

### ISSUE THREAD

**Issue by ajinkyashukla** [QuizandSurveyMaster/quiz_master_next#2184]
## Site Info
WordPress Version: 6.2
QSM Version: 8.1.5
Browser: FireDragon 111.0

## General description
The Quizzes & Surveys section lists all the quizzes

Link to quiz or screenshot (if relevant): 

## Feature request
As a logged in author, the Quizzes & Surveys section should only  list the quizzes that I have created.

**Comment by zubairraeen** [comment]
I have already released this feature please review
