### ISSUE TITLE
Deprecation notices in the Admin Dashboard with PHP 8.1 if WP_DEBUG is enabled

### ISSUE THREAD

**Issue by jonas-herkelmedia** [QuizandSurveyMaster/quiz_master_next#2188]
## Site Info
WordPress Version: 6.2
QSM Version: 8.1.6
Browser: Google Chrome Version 113.0.5672.63

## General description
I am getting deprecation notices everywhere in the Admin Dashboard with PHP 8.1 if WP_DEBUG is enabled.

## Expected behavior
No deprecation notices everywhere in the Admin Dashboard because it bothers me while developing a theme or plugin.

## Actual behavior
Notices on all my websites.

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in C:\Users\Jonas\Local Sites\test\app\public\wp-includes\functions.php on line 7053
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\Users\Jonas\Local Sites\test\app\public\wp-includes\functions.php on line 2165
Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in C:\Users\Jonas\Local Sites\test\app\public\wp-includes\functions.php on line 7053
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\Users\Jonas\Local Sites\test\app\public\wp-includes\functions.php on line 2165
Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in C:\Users\Jonas\Local Sites\test\app\public\wp-includes\functions.php on line 7053
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in C:\Users\Jonas\Local Sites\test\app\public\wp-includes\functions.php on line 2165

## Steps to reproduce the behavior
Install the plugin on a fresh WP Site with PHP 8.1, set WP_DEBUG to true and go to the Admin Dashboard.

**Comment by zubairraeen** [comment]
It's not an issue related to the QSM plugin, but rather a WordPress error.
So closing this ticket
