### ISSUE TITLE
Leaderboard should show overall score!

### ISSUE THREAD

**Issue by PhilSil** [QuizandSurveyMaster/quiz_master_next#221]
I have many different quizes now. But all are the same topic. The user wants to see an overall ranking of all scores from all quizes (sum of the scores).
Exaple: User scored 5 points in quiz one and 8 points in quiz 2. --> 5 + 8 = 13.

**Comment by fpcorso** [comment]
Greetings PhilSil:

Thank you for choosing to use this plugin! Great idea! We will keep this on the list of requested features for you.
