### ISSUE TITLE
Pay wall ability through the results pages

### ISSUE THREAD

**Issue by gamekid88** [QuizandSurveyMaster/quiz_master_next#222]
Users want to be able to set up a pay wall system when the results pages are generated. This would prevent the users from seeing the results or moving on to the next quiz without paying.

**Comment by fpcorso** [comment]
I had another user request this feature. This user wants all visitors to be able to view and take the quiz. After last question user will add his name and e-mail address. Next step will be redirected to checkout where the visitor can pay. After payment, the user can see the results page and the certificate will be sent to his email.
