### ISSUE TITLE
Bug with special Characters

### ISSUE THREAD

**Issue by PhilSil** [QuizandSurveyMaster/quiz_master_next#230]
I have a test with blanks.

correct word is: "plangemäß" 

The result will never be correct somehow. Probably because of the special character.

Can you fix this please, as it is very essential for our use. :)
Thank you

**Comment by fpcorso** [comment]
Interesting. I will get this tested and discover what is going on. I will have a fix for you shortly. Thank you for reporting!

**Comment by PhilSil** [comment]
Could you please tell me why the user has only 12/13 correct? I have a lot of such problems...
I really need a fast fix because I am already selling a digital product where users do such quizes...

Quiz Ergebnisse für Aufgeheizte Stimmung: Farbbeutelanschlag auf Bildungseinrichtung

Name: Rami 

Email: None 

Score: 12/13 or 92% or 0 points 
Antworten:

The user took 912 to complete quiz. 

Comments entered were: 

The answers were as follows: 

Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.



Unbekannte Täter verübten in der letzten Woche einen Anschlag auf die __________. 
Deine Antwort: Landeszentrale für politische Bildung 
Richtige Antwort: Landeszentrale für politische Bildung
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


Die Polizei teilte mit, dass das Gebäude der __________ in der Nacht zu Donnerstag mit mehreren Farbbeuteln beworfen worden war. 
Deine Antwort: staatlichen Bildungseinrichtung 
Richtige Antwort: staatlichen Bildungseinrichtung
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


__________ 
Deine Antwort: Außerdem seien einige Fensterscheiben zu Bruch gegangen. 
Richtige Antwort: Außerdem seien einige Fensterscheiben zu Bruch gegangen.
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



Der Innenminister besichtigte höchstpersönlich den Tatort in der __________ und bezifferte den Schaden auf schätzungsweise 10.000 Euro. 
Deine Antwort: Landeshauptstadt 
Richtige Antwort: Landeshauptstadt
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


__________ allem der offenkundig politisch motivierte Hintergrund des Angriffs gegen eine überparteiliche Institution. 
Deine Antwort: Ihn bewege, so der Minister, vor 
Richtige Antwort: Ihn bewege, so der Minister, vor
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


Nach dem aktuellen Stand der Ermittlungen sei noch unklar, welcher politischen Strömung die Täter angehören, die kein __________. 
Deine Antwort: Bekennerschreiben hinterließen 
Richtige Antwort: Bekennerschreiben hinterließen
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


In den letzten Monaten hatte sich die Landeszentrale im Rahmen ihrer Kampagne „__________“ für eine verstärkte Teilhabe der Bürger an der politischen Diskussion eingesetzt. 
Deine Antwort: Demokratie stärken 
Richtige Antwort: Demokratie stärken
Ergebnis: 

Bitte geben Sie die fehlenden Wörter ein.


Unter anderem wurden ihre Räumlichkeiten für eine Pressekonferenz von __________ zur Verfügung gestellt. 
Deine Antwort: Islamkritikern 
Richtige Antwort: Islamkritikern
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



In der Öffentlichkeit war dem Leiter der Einrichtung daraufhin vorgeworfen worden, er habe das Gebot der __________ massiv verletzt. 
Deine Antwort: Überparteilichkeit 
Richtige Antwort: Überparteilichkeit
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



Die Landeszentrale erklärte, dass die __________ keinerlei Auswirkungen auf die laufende Arbeit haben werde. 
Deine Antwort: Attacke 
Richtige Antwort: Attacke
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



Eine Veränderung des Bildungsprogramms wolle man sich nicht aufzwingen lassen, sagte eine __________. 
Deine Antwort: Referatsleiterin 
Richtige Antwort: Referatsleiterin
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.



Man werde sich einem Diktat radikaler __________ keinesfalls unterwerfen. 
Deine Antwort: Gewalttäter 
Richtige Antwort: Gewalttäter
Ergebnis: 

Bitte geben Sie das fehlende Wort ein.


Die Veranstaltungen der __________ sollten bereits am Abend nach dem Anschlag plangemäß stattfinden. 
Deine Antwort: Bildungsinstitution 
Richtige Antwort: Bildungsinstitution

**Comment by zubairraeen** [comment]
Hi 
This issue is fixed you can test now
