### ISSUE TITLE
Incorrect Characters should be highlighted

### ISSUE THREAD

**Issue by PhilSil** [QuizandSurveyMaster/quiz_master_next#231]
When usind "Fill the blank" on the result page the words used are just printed out as is. 
It would be very helpful for the users if they could see what they did wrong. 

Can you implement this feature?

**Comment by fpcorso** [comment]
Can you elaborate a little more on this one? If the user got the question wrong, do you want the correct answer to be highlighted?

**Comment by PhilSil** [comment]
Use Case:
A dog is a nice %BLANK%. 

Correct Answer: animal
Wrong Answer: aminal

So the wrong characters in the wrong answer should be highlighted.

**Comment by fpcorso** [comment]
Ah! That makes much more sense now. That will be a difficult one to build due to the nature of how we currently are handling the answers. Hmmm... I will take a look and see if I can get this done as soon as possible for you.

Thank you again for adding so many ideas here. I do appreciate your input.

**Comment by PhilSil** [comment]
Maybe a first version could be to just mark the wrong answer in a different color because if you have 20 questions and only one answer was incorrect, you have to search for a long time. This is not very good user experience I think. What do you think?

**Comment by dmknows** [comment]
Hello,
 Do you have any updates on this issue? I want to highlight the wrong answers and rights answers. It can be something like a red error sign on the wrong and a green one on the right answer. Please add this feature, I have been requesting for the same since long.

Thank you in advance
