### ISSUE TITLE
In randomly generated quizzes, question description is displayed with HTML tags.

### ISSUE THREAD

**Issue by Anupama-Dikkumbura** [QuizandSurveyMaster/quiz_master_next#2367]
## Site Info
WordPress Version: 6.3.1
QSM Version: 8.1.16
Browser: Chrome

## General description
Bug: In randomly generated quizzes, question description is displayed with HTML tags.

Link to quiz or screenshot (if relevant): 
![image](https://github.com/QuizandSurveyMaster/quiz_master_next/assets/35387310/0c3a06ca-55ed-4218-bf22-d2eac0477c9f)

## Expected behavior
The quiz description should be displayed properly without HTML tags.

## Actual behavior
In randomly generated quizzes, question description is displayed with HTML tags.

## Steps to reproduce the behavior
1. Create a few questions with a question description.
2. Create a quiz with random questions, including previously created questions.

**Comment by zubairraeen** [comment]
Hello,

We have resolved and released an update for this issue. Please verify it with the latest version of the QSM plugin.

Thank you.
