### ISSUE TITLE
Persistent Quotation Mark Encoding Issue in Custom CSS Editing

### ISSUE THREAD

**Issue by nicolasvegaabril** [QuizandSurveyMaster/quiz_master_next#2412]
## Site Info
WordPress Version: 6.4.2
QSM Version: 8.1.19
Browser: Chrome

## General description

When modifying custom CSS within a theme, saving the code results in the persistent encoding of quotation marks, even after multiple encoding attempts. Moreover, when inspecting the CSS, the quotation marks appear as `&quot;`. This presents an issue, as subsequent saves trigger additional encoding during the post request process.

Link to quiz or screenshot (if relevant): 

![image](https://github.com/QuizandSurveyMaster/quiz_master_next/assets/47582784/bbfe8ff0-e87b-4d46-95cd-66b97292a7f9)

## Expected behavior

The CSS code needs to be decoded before presenting it to the user, and the save button should avoid double encoding.

## Actual behavior

I've included the details in the general description.

## Steps to reproduce the behavior
Write some custom CSS using quotation marks, then proceed to save it. Afterward, save it again.

**Comment by zubairraeen** [comment]
I encountered this issue in QSM version 8.1.19, where quotation marks in custom CSS were persistently encoded as ". However, this issue has been resolved in the current version, and it no longer occurs.

Thank You
