### ISSUE TITLE
Plugin CSS affecting unrelated parts of admin section

### ISSUE THREAD

**Issue by siliconforks** [QuizandSurveyMaster/quiz_master_next#2659]
## Site Info
WordPress Version: 6.6.2
QSM Version: 9.1.3
Browser: Any

## General description

The plugin's CSS is affecting the layout of unrelated parts of the admin section.

For example, go to Settings &rarr; General and look at the "Date Format" and "Time Format" sections.

## Expected behavior

Without the plugin installed, it looks like this:

![without-plugin](https://github.com/user-attachments/assets/356ac86c-8676-4a93-bc02-cd757fa385ea)

## Actual behavior

With the plugin, it looks like this:

![with-plugin](https://github.com/user-attachments/assets/4008bd7e-7560-4da8-b324-7ea407b0f2e8)

Note that the "Custom:" option has been split into two lines.  This is because the file `css/qsm-admin.css` is loaded on all pages in the admin section, and it has this code:

https://github.com/QuizandSurveyMaster/quiz_master_next/blob/0c26ba8c9737a5cea0f090658b9c9dd75c8849e3/css/qsm-admin.css#L1381-L1384

## Steps to reproduce the behavior

Just log in to the admin section and go to Settings &rarr; General.  (Similar effects can be seen on other admin pages, too.)

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by zubairraeen** [comment]
Issue fixed
