### ISSUE TITLE
Quiz Prequisites - Require Passing Of Quiz Before Gaining Access To Next Quiz

### ISSUE THREAD

**Issue by gamekid88** [QuizandSurveyMaster/quiz_master_next#267]
Admins want to be able to schedule quizzes so that certain quizzes must be completed before others can be completed.

**Comment by fpcorso** [comment]
I had another user request the ability to only give access to the next quiz once a user passes the first quiz.

**Comment by fpcorso** [comment]
I just had another request for this. I think it's time to move this into the planning phase.
