### ISSUE TITLE
%USER_NAME% shortcode is not working in Result page

### ISSUE THREAD

**Issue by artemis15** [QuizandSurveyMaster/quiz_master_next#291]
Hi,

Thanks for creating this useful plugin. I was using it and it was working fine. But now I changed the Result page template and included "%USER_NAME%" for providing username. But this didn't work while providing the result page. Although this "%USER_NAME%" worked while sending the email to user. 

Could you please rectify this issue.

**Comment by fpcorso** [comment]
Hey @artemis15, I just checked on my test site and this works correctly in the latest version of the plugin there. Can you screenshot how you have the results pages set up? Also, are you using any other variables in the results pages?

**Comment by artemis15** [comment]
Hi,

Attached the screenshot of my result page

![capture](https://cloud.githubusercontent.com/assets/8123664/10148123/6ea6a6f2-664f-11e5-8359-0c2a55c6cc91.PNG)

**Comment by fpcorso** [comment]
Hey @artemis15, is this your only result page or do you have others? If so, is this the default? I see that you use the name variable twice, does either one get converted correctly? If you remove one of them, does the other convert correctly?

**Comment by artemis15** [comment]
Hi,

No, none of them is working fine.

**Comment by zubairraeen** [comment]
Hi, 

The issue has been resolved and is working correctly in the latest QSM version. Therefore, we are closing this ticket. 

Thank you!
