### ISSUE TITLE
Teachers (User Roles) And Classes (Groups)

### ISSUE THREAD

**Issue by WhatsNewSaes** [QuizandSurveyMaster/quiz_master_next#306]
Hi there, I am evaluating a number of different quiz plugins and was wondering if this plugin has the ability to show specific admins (teachers) results for people in their group (class). 

It's great that I can see all stats, but can that be partitioned out to show teachers specific stats of their students from their quizzes / tests.

Thanks for any feedback!
Seth

**Comment by fpcorso** [comment]
Hey Seth ( @WhatsNewSaes ), I somehow missed your issue. Sorry about that. This plugin does not currently have a feature to breakdown the tests to different teachers and classes. That is a cool idea and will add that to my list of requested features.

**Comment by WhatsNewSaes** [comment]
Sounds good, thanks @fpcorso!

**Comment by fpcorso** [comment]
Ah, just realized that I already had a User Role issue opened #203. I'll close the other issue since we have already started conversation here.

I have begun outlining this capability and will hopefully have some more information soon.
