### ISSUE TITLE
Timer Per Question

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#308]
User would like to have the timer reset for each question. For example, he wants to enter that a quiz taker has 3 minutes to answer each question. Once the quiz taker goes to the next question, the timer resets to 3 minutes.

**Comment by sriordan9** [comment]
Another request for this feature has been received

**Comment by adminrj** [comment]
It would be perfect to have a timer for a question. How much it cost frank corso?

**Comment by vikasprogrammer** [comment]
Sure, we will include this in our upcoming releases.
