### ISSUE TITLE
Greater control over scoring

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#347]
Some admins would like greater control over how the questions scores are combined. For example, one user would like the ability to multiple Q1 and Q2 points to display that total.

Can possibly be done with new template variable.

**Comment by sriordan9** [comment]
A user has also requested template variables for point scores as percentages of the total quiz points. Example: Quiz total points are 50, but user only received 25 then score would be 50%

They would also like to have percentage scores based on points but for categories.
