### ISSUE TITLE
New stats page showing count of completed lessons

### ISSUE THREAD

**Issue by johnala** [QuizandSurveyMaster/quiz_master_next#358]
We use the quiz master to have student fill out worksheets after listening to an audio lesson. We would like a summary by student name showing number of lessons completed. Could do in Excel but would be great if in tool summary page was available. Additionally ability to sort by name or number completed.

**Comment by fpcorso** [comment]
Greetings @johnala,

Thank you for choosing to use this plugin! I want to make sure I understand your need correctly: You need a report/stats page that shows the # of completed quizzes? So, something like this:

Frank Corso | 1 quiz
johnala | 5 quizzes
John Smith | 10 quizzes

**Comment by johnala** [comment]
Yes. That would be what we need. Even better would be the ability to have
that in a variable so I can put it in the end of quiz text. Like this

Congratulations %name% you just completed lesson %quizecount% of the Honor
Corps series. Keep up the good work.



*John Ala*   Web design and Social Media Consulting
3 Pillars Group, LLC              Excellence ∙ Service ∙ Value
Phone: *(720) 375-5662*
Email: *john@3PillarsGroup.com*
Website: *http://www.3pillarsgroup.com <http://www.3pillarsgroup.com>*
Address: *Highlands Ranch, Colorado*
<http://www.facebook.com/3PillarsGroup>
