### ISSUE TITLE
Labeled Score Range & Facebook Share Image

### ISSUE THREAD

**Issue by Fishuu** [QuizandSurveyMaster/quiz_master_next#366]
Hi! Related to issue #171 (https://github.com/fpcorso/quiz_master_next/issues/171), it'd be great if you could set the score range to have separate text labels like in a Personality Quiz. For example, if they scored somewhere between "15 to 30", the result named would be "Superhero!" If there could be an option to just use the text labels rather than numerical points, that works too.

This way, when the quiz is shared via Facebook, the link text can say something like: "Your personality is ______! Click here to find out your personality!"

Currently, it only seems to pass a numerical value with %POINT_SCORE%.

Likewise, if the Facebook image could be grabbed via the inserted image on the individual quiz results page.

Hope that makes sense. Thanks!

**Comment by fpcorso** [comment]
Hey @Fishuu,

Thank you for choosing to use this plugin! At the moment, I do have an addon that adds a variable you can use to show different words/phrases based on score. You can see it in action here: http://quizandsurveymaster.com/extra-template-variables-documentation/

However, I do plan on re-writing the social media sharing system to make it easier to use and allow you to customize it a lot more. Unfortunately, I do not have a time frame for when that new system will be ready but am hoping to have it ready by 4.8

**Comment by Fishuu** [comment]
Awesome! Keep up the good work :)
