### ISSUE TITLE
Master Question Bank

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#39]
User wants to have a question bank to choose quizzes from. I'm thinking of adding a new page to the menu that serves as a master question bank. Users could add questions to it then create different quizzes from selected questions or by questions in certain categories or even by question type.

**Comment by OC2PS** [comment]
This is quite important. At some point, you might even enable quizzes that randomly pick x questions from the question bank.

**Comment by fpcorso** [comment]
@gamekid88 I decided to drop this out of this release since we are going to be converting the questions to custom post types in the a few updates. It will be better to build the master bank then. If not, we will have to re-write it when we change the question system.

**Comment by sriordan9** [comment]
Another user has made a similar request for this. 

User email: "As far as the Question Bank is concerned, I would like to add a question, add the Category and the question automatically gets populated in the Category Quiz as well as remain in the Bank. This particularly when a new question is being added to an existing category."
