### ISSUE TITLE
Analyse Level Of Difficulty

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#40]
User wants the plugin to review percent of users that got question right versus percent that got question wrong to mark a level of difficulty on the question

**Comment by OC2PS** [comment]
To prevent wild changes in difficulty levels of questions when they are first created (i.e. when very few people have answered the question) Admin should be able to define the number of quiz-takers needed before difficulty level is shown.

So, Admin may say show me difficulty levels only after a question has been attempted by 60 people.

Also, Admin should be able to check a box that allows him/her to define whether the difficulty level will be shown only to admin or to quiz takers too.
