### ISSUE TITLE
Plugin Conflict with SEO Smart Links Plugin

### ISSUE THREAD

**Issue by dukeran** [QuizandSurveyMaster/quiz_master_next#409]
A user reported that the submit button doesn't work if SEO Smart Links is enabled

**Comment by fpcorso** [comment]
Trying to debug this now @dukeran for the update I am working on. I installed SEO Smart Links and the submit button still works correctly. Not sure. Do you know if the person who reported this still uses QSM? Maybe we can do a little more debugging by seeing what admin-ajax.php is showing on the Network tab.

**Comment by zubairraeen** [comment]
Hi
SEO Smart Links Plugin has been closed as of September 5, 2022 and is not available for download. Reason: Security Issue.
Therefore, we are closing this ticket.

Thank you!
