### ISSUE TITLE
All answer choices shown in the results page 

### ISSUE THREAD

**Issue by dukeran** [QuizandSurveyMaster/quiz_master_next#419]
User requested a variable that would show all the answer choices in the results page.

**Comment by fpcorso** [comment]
So, @dukeran are they looking for all the answers the user can choose from? If the question is a multiple choice question which has 3 possible answers, they want to display all three answers when showing the questions?

This would be a new variable to enter into the %QUESTIONS_ANSWERS% template, correct?

**Comment by dukeran** [comment]
@fpcorso That's what it appears to be, client says that because we do not have this feature possible that he cannot use the plugin. I am assuming the client wants a way to show all the answers possible on a results page and then somehow demarcate the correct one and then put the quiz taker's answer below?
