### ISSUE TITLE
Auto-advance pagination upon selecting answer

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#442]
## General description

Admin would like the ability to have the plugin automatically advance to the next page when a quiz taker selects an answer.
## Feature request

Admins have a variety of quizzes and surveys that are only one question per page. They feel that they could reduce the amount of necessary clicks/taps by eliminating the need to click on the "Next" button. One solution that was requested was to have the plugin automatically advance to the next page when a quiz taker selects an answer.

**Comment by sriordan9** [comment]
Another request has been made for this feature

**Comment by sriordan9** [comment]
Another request has been made for this feature
