### ISSUE TITLE
%CERTIFICATE_LINK% conflict with other template variables

### ISSUE THREAD

**Issue by MarcGuay** [QuizandSurveyMaster/quiz_master_next#461]
Quiz And Survey Master v4.7.6
QSM - Certificate v0.1.0

After configuring my certificate settings, I have put all of the variables in the Results Page as a test.  When the %CERTIFICATE_LINK% template variable is included, it is the only one to be parsed.  So I see "%POINT_SCORE% - Score for the quiz when using points %AVERAGE_POINT% - The average amount of points user had per question %AMOUNT_CORRECT%" etc except for %CERTIFICATE_LINK% which has been corrected converted into a link.  If I remove the certificate variable and leave the rest, they are parsed correctly. 

Let me know if I can provide any more details.
Marc

**Comment by MarcGuay** [comment]
If I change the priority of the `mlw_qmn_template_variable_results_page` filter in the QSM - Certificate plugin from 1 to 10 (to match the ones in the main QSM plugin) the problem is resolved. 

qsm-certificate.php line 76
`add_filter( 'mlw_qmn_template_variable_results_page', 'qsm_addon_certificate_variable', 10, 2 );`

**Comment by MarcGuay** [comment]
It actually doesn't seem to solve the problem entirely.  I have another survey where if I *start* the Results Page template with "%CERTIFICATE_LINK%" it works fine, but if I place anything at all before it, it is not parsed.

**Comment by dukeran** [comment]
@MarcGuay 
Thanks for letting us know and for keeping us updated with what went wrong. We hope to have this bug fixed as soon as possible!

Cheers
