### ISSUE TITLE
E-Mail Sent to user doesn't work correctly anymore

### ISSUE THREAD

**Issue by mike2700** [QuizandSurveyMaster/quiz_master_next#462]
My settings worked good in the past for e-mail sent to user, but now the settings for Email sent to user doesn't seem to be reading the values of the variables anymore...weird. The variables show in the e-mail exactly how it looks in the settings box. I recently added the certificate add-on if that makes any difference and by the way I am using the latest version of the software, version 4.76 

For example.  This is what I put in the E-mail sent to User box:

Thanks  %USER_NAME% for taking our AGC range and safety orientation quiz.

Club: %USER_BUSINESS%

Congratulations! You passed!

Certificate Link: %CERTIFICATE_LINK%

%COMMENT_SECTION%

**and this it what I receive in my email**

Thanks %USER_NAME% for taking our AGC range and safety orientation quiz. 

Club: %USER_BUSINESS% 

Congratulations! You passed! 

Certificate Link: Download Certificate **--------->(I do however get the link) <---------------** 

%COMMENT_SECTION%

**Comment by mike2700** [comment]
UPDATE:  After deactivating the new certificate add-on, the e-mail system seems to be working again.  I'm not going to be updating to 5.0 until I am sure that what seems to me to be an obvious bug is resolved.  Quiz & Survey Master is useless to me unless the certificates and e-mails work correctly.

**Comment by dukeran** [comment]
Hey @mike2700 

Thanks for letting us know about the bug! We hope to have it fixed before the update comes out.

Cheers

**Comment by produktive** [comment]
@mike2700 

You're right in that it's a problem with the certificate addon. Disable the addon and use the old (beta/included) certificate system and it should work.
