### ISSUE TITLE
Add Likert Scale Question Type

### ISSUE THREAD

**Issue by jonesej20** [QuizandSurveyMaster/quiz_master_next#465]
## Feature request

I would like to be able to create a survey and have the answers to questions render as a Likert Scale (https://en.wikipedia.org/wiki/Likert_scale). An example of the code that could be used to render this can be found here (https://codepen.io/Buttonpresser/pen/qiuIx). The option would then exist in the dropdown for question type. Thank you for the consideration.

**Comment by sriordan9** [comment]
Another request has been received for this feature
