### ISSUE TITLE
Possible issue with multiple quizzes on one page

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#483]
A few users reported a new bug where they can no longer have more than one quiz/survey on a page. This plugin has supported that for a very long time so it shouldn't have any issue now and I cannot reproduce it on any test site. However, since we have now had a few users report it, it should become a reported bug here.

**Comment by zubairraeen** [comment]
Hi, 

The issue has been resolved and is working correctly in the latest QSM version. Therefore, we are closing this ticket. 

Thank you!
