### ISSUE TITLE
Admin Emails Only Being Sent To First Email Address

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#486]
## General description

A user is reporting an issue where they have multiple admin emails entered using the correct format but the admin email is only being sent to the first email.

**Comment by fpcorso** [comment]
Hmmm...still can't replicate this issue.

**Comment by zubairraeen** [comment]
Hi, 

The issue has been resolved and is working correctly in the latest QSM version. Therefore, we are closing this ticket. 

Thank you!
