### ISSUE TITLE
Categories for  Answers & Percentage Results in Pie Chart 

### ISSUE THREAD

**Issue by RMickler** [QuizandSurveyMaster/quiz_master_next#487]
## Feature request

It would be great if categories could be added to multiple choice answers. I am putting together a Find Your Interior Design Style quiz. For example I'd like to show 4 images, one from each of 4 design styles and have the user pick their favorite (each answer representing a different category). As the existing quiz works now, I can only categorize questions (not answers) which greatly increases the number of questions I must ask to assess the user's preference. At the end of the quiz, I'd like to be able to tell them, "Your design style is 65% Traditional, 20%Country and 15% Contemporary. It would be great if a pie chart on bar graph was an option as well.

**Comment by sriordan9** [comment]
A second request has been received for this feature.
