### ISSUE TITLE
Numbered or bullet lists in question gets broken when editing question

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#493]
## General description
When using numbered lists or bullets in a question, it gets broken when editing the question.

## Steps to reproduce the behavior
Create a new question and use a numbered list or bullets. The list will appear correctly in the questions list and in preview. However, if you try to edit the question, lots of new lines will be added and will break the numbers in the numbered list.

**Comment by dkruchok** [comment]
Hey,
any progress here?

**Comment by sriordan9** [comment]
Another request has been made to fix this bug

**Comment by zubairraeen** [comment]
Hi,  

The issue has been resolved, tested, and is not replicating in the latest QSM version. Therefore, we are closing this ticket.  

Thank you!
