### ISSUE TITLE
Adding Ability To Choose X Amount For Multiple Response

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#495]
## General description
How the multiple response question type is set up currently, several users would like the ability to set how many answers can be chosen. If not, the user can just select all the answers to receive the points.

## Expected behavior
When using points, if only two answers give users points in a multiple response question, the user should not receive points if selecting all answers or an option for the admin should be available for these cases.

## Actual behavior
When using points, if only two answers give users points in a multiple response question, the user can just select all answers to receive the points.

**Comment by zubairraeen** [comment]
Hi,  

We have added an option to set a limit for selecting the maximum number of answers in multi-response questions.  herefore, we are closing this ticket.

Thank you
