### ISSUE TITLE
Rare Case Where Quiz Doesn't Submit When User Or Admin Email Turned On (500 Error)

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#505]
## General description
A handful of users are experiencing a strange bug where if the user or admin emails are turned on, then the AJAX for when submitting the form returns a 500 error. This causes the results to not be saved and any user/admin emails to not be sent out.

**Comment by fpcorso** [comment]
Hmm...testing on one user's site appears that the 500 error is coming from the wp_mail function call itself....strange

**Comment by fpcorso** [comment]
Another user has reported this issue. Asked for System Info and Plugin Conflict Check.

**Comment by fpcorso** [comment]
Another user has reported this issue. Asked for system info, check email, and plugin conflict check.

**Comment by fpcorso** [comment]
Ah, I finally got some debug info for this:

[30-Jan-2017 16:11:06] PHP Fatal error:  Uncaught exception 'phpmailerException' with message 'Invalid address:  (setFrom) g' in /home2/gritz/public_html/wp1/wp-includes/class-phpmailer.php:1023

Stack trace:
#0 /home2/gritz/public_html/wp1/wp-includes/pluggable.php(352): PHPMailer->setFrom('g', 'g', false)
#1 /home2/gritz/public_html/wp1/wp-content/plugins/quiz-master-next/php/class-qmn-quiz-manager.php(1083): wp_mail('support@mylocal...', 'Quiz Results Fo...', '<div class='qmn...', 'From: g <g>??', Array)
#2 /home2/gritz/public_html/wp1/wp-content/plugins/quiz-master-next/php/class-qmn-quiz-manager.php(595): QMNQuizManager->send_user_email(Object(stdClass), Array)
#3 /home2/gritz/public_html/wp1/wp-content/plugins/quiz-master-next/php/class-qmn-quiz-manager.php(529): QMNQuizManager->submit_results(Object(stdClass), Array, Array, Array)
#4 /home2/gritz/public_html/wp1/wp-includes/class-wp-hook.php(298): QMNQuizManager->ajax_submit_results('')
#5 /home2/gritz/public_html/wp1/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(Array, Array)
#6  in /home2/gritz/public_html/wp1/wp-includes/class-phpmailer.php on line 1023

**Comment by fpcorso** [comment]
The user checked the settings and the from email is definitely a full email address.

**Comment by etvarun** [comment]
Issue is not reproducing with latest versions. Closing this.
