### ISSUE TITLE
Pagination doesn't work if JS script added to head

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#511]
## General description
Some plugins and cache systems move the scripts from the end of the body to the head element. Since qmn_quiz_data is defined in the body of the shortcode, this results in a "Uncaught ReferenceError: qmn_quiz_data is not defined at qmnInit".

**Comment by zubairraeen** [comment]
Hi,  

It is necessary to load the quiz JavaScript in the footer for the quiz to function correctly. Therefore, we are closing this ticket.

Thank you!
