### ISSUE TITLE
Bug: Quiz will not submit (no error msg), multiple users reporting issue

### ISSUE THREAD

**Issue by TamiAdmin** [QuizandSurveyMaster/quiz_master_next#522]
Suddenly, users cannot submit my online questionnaire. There is no progress, they hit the submit button and nothing happens. The questions are all displayed, however the  the number of questions per page is not displaying correctly, and the message template asks are not displaying correctly although the settings in the admin pages have not changed. Multiple users are reporting the problem. 

There is no error message, no transfer to another page, they can fill out the questions and then cannot submit.

 All WordPress themes are up to date.

As near as I can tell, the last successfully submitted quiz was January 30th. Then I updated the Quiz Master next plugin, and it stopped working. This has happened one other time, when an update to the plugin has resulted in a fatal failure of the submission of results.

**Comment by portcomms** [comment]
I am having this same issue.

Was this ever resolved?

**Comment by TamiAdmin** [comment]
This issue remains unresolved.

**Comment by fpcorso** [comment]
Hey @portcomms and @TamiAdmin. This may be related to #505. If you have any emailed enabled for the quiz/survey, can you temporarily turn it off to see if the quiz/survey will then submit?

**Comment by TamiAdmin** [comment]
No this does not resolve the issue. Turned off all of the e-mail
notifications on the E-mails page in the admin.

When I go to the questionnaire link (
http://www.anamacarairishsetters.com/anamacara-irish-setters-puppy-and-adult-dog-questionnaire/)
part of the introductory text appears twice and the font size varies
(neither of which occurs in the Text settings in the admin). All of the
questions appear on the same page, the admin settings specify 10 questions
per page. Get to the end and hit the submit button. Nothing happens.

Same problem as before, this is unresolved.

**Comment by xdnv** [comment]
I was able to fix the issue for my situation.

The mlw_results table stores quiz_results field as TEXT which is 65k bytes long.
My questionnaire with 200+ questions with non-latin chars took 75kbytes, so Wordpress just silently skipped the insert in $wpdb->insert call.
That's common behavior for Wordpress when DB field is smaller than the data provided.

Changing type of quiz_results to MEDIUMTEXT (16M size) completely solved the issue for me.

Would be nice to see some option a-la "support for big questionnaires" in future QSM releases with support of such a big field size.

**Comment by etvarun** [comment]
We have updated the plugin to set quiz_results to MEDIUMTEXT (16M size) by default.
