### ISSUE TITLE
Hang on submit AND no results email sent after submit

### ISSUE THREAD

**Issue by xandermaccyd** [QuizandSurveyMaster/quiz_master_next#549]
Love this plugin but have just started to experience some very weird issues and can't see them reported anywhere else on here.

I can submit quizes (and successfully receive results) whenever I test using my desktop, laptop, tablet or phone. But 2 issues are repeatedly cropping up with lots of the people are who are trying to submit our quizzes...

a) Upon submit, the quiz page simply hangs indefinitely. No result is recorded on the DB. This is independent of device or browser and has happened with lots of people.

b) Upon submit, the result IS recorded by the DB (we can see the result inside the plugin)...but the user doesn't get sent their result email. This has happened to lots of people.

Would be very grateful for help with this, an understanding if this is a WP or plugin issue.

http://jodigoldman.co.uk/quiz/pi-factor-quiz-lp/
http://jodigoldman.co.uk/quiz/pi-factor-quiz-ffp/

Site Information

Site URL: http://jodigoldman.co.uk
Home URL: http://jodigoldman.co.uk
Multisite: No
WordPress Information

Version: 4.7.5
Language: en_US
Active Theme: JodiGoldman 1.0.0
Debug Mode: Disabled
Memory Limit: 40M
Plugins Information

Must Use

System Plugin: 3.7.0
Active

CMB2: 2.2.4
Contact Form 7: 4.7
Duplicate Post: 3.2
Force Regenerate Thumbnails: 2.0.6
PixelYourSite: 5.0.1
Quiz And Survey Master: 5.0.1
Redux Framework: 3.6.4
Search Engine Visibility: 0.5
Share Buttons by AddThis: 5.3.5
Simple 301 Redirects: 1.07
TinyMCE Advanced: 4.4.3
Virtual Robots.txt: 1.8
WordPress Importer: 0.6.3
WP101 Video Tutorials: 0.3
WPBakery Visual Composer: 5.0.1
Wpdevart Facebook comments: 1.7.3
WP Smush: 2.6.2
Inactive

Akismet Anti-Spam: 3.3.2
GoDaddy Email Marketing: 1.2.0
Server Information

PHP : 5.6.27
MySQL : 5.6.32
Webserver : Apache
QMN Information

Initial Version : 5.0.1
Current Version : 5.0.3
Total Quizzes : 6
Total Active Quizzes : 2
Total Questions : 62
Total Active Questions : 40
Total Results : 56
Total Active Results : 21
QMN Recent Logs

Log created at 2017-06-05 19:15:21 : Error 0008 - from 
Log created at 2017-06-04 20:31:20 : Error 0014 - from 
Log created at 2017-06-04 20:28:24 : Error 0014 - from 
Log created at 2017-06-04 20:23:44 : Error 0014 - from 
Log created at 2017-05-20 19:26:39 : Error 0008 - from

**Comment by fpcorso** [comment]
Hey @xandermaccyd 

Thank you for choosing to use this plugin! I just went to both quizzes linked in the issue and submitted several times. You may want to delete my entries if you are doing any analysis on answers.

Hmmm... for bug 1, I wonder if it is the same issue from #505. I submitted 4 times but was not able to replicate this one. How often does this one occur? On one quiz (the pi-factor-quiz-ffp one), the results took a while to load the one time (about 10 seconds) but did load eventually.

For bug 2, this is something that has come up a lot over the years. Usually, using an SMTP system fixes this though. I took your quizzes multiple times with different email address to test different domains and clients but received the email all 4 times. How often does this bug occur?

I agree that we can rule out any device or browser issue.

Do you have access to a PHP error log to see if there is anything in there? Would it be possible to temporarily turn on WP Debug mode, submit the quizzes a few times until you encounter one of the bugs, turn off WP Debug mode, and then copy contents of the debug log here?

**Comment by xandermaccyd** [comment]
Hey Frank,

Big thanks you for getting back to us. Afraid we have run out of time - our
quizes are a big part of our marketing and we've got to get going, so we've
had to go with a different option: this is a shame as we are real fans of
your plugin.

Re: bug one - it's tricky, as I cannot replicate...however, lots of people
have sent me screenshots showing the quiz hanging. I am NOT a techie, but I
do wonder if it has something to do with tags and bits of html creeping
onto pages and confusing the system. I only say this because my quizes ran
smoothly until I started doing lots of rewriting, cutting and pasting into
the results page etc. I wonder if there is something on the results page
(but not visible in the text editor) that causes the end of the quiz to
stall. Of course, if that is when the email is triggered (prior to the
results page appearing), it could also be related to bug 2. Incidentally,
one one occasion, when someone was experience the hanging problem...I was
temporarily able to fix it...by turning admin emails off: but after this
allowed one person to re-take the quiz and get past the hang...for another
person, for whom the quiz had been working, this caused the hang to occur.

As for bug two...this happens about 50% of time...although I can't detect
any rhyme or reason to it. I really doubt this will be of any help, but
here is a screen grab (see attached) of three fails from my SMTP
service...like I said, I'm not a techie at all, but it's interesting that
all 3 messages seem to be about different things.

We are super busy, but if we eventually have time we'll try and check the
PHP error log + run WP Debug Mode - however, I think we'll have to leave it
for now.

All the best and thanks once again for coming back to us,
Alex McDonald & Jodi Goldman

**Comment by cromat** [comment]
Hi,
I have encountered same problem. I found out it was due to wrong email message template content. I have put variables in wrong format, precisely, it was typo in %CATEGORY_POINTS%%/CATEGORY_POINTS%. So check your email templates and also result page template.
