### ISSUE TITLE
%USER_ANSWER% display empty

### ISSUE THREAD

**Issue by 284247028** [QuizandSurveyMaster/quiz_master_next#550]
<img src="http://www.aliacp.cn/wp-content/uploads/2017/06/a.png" width = "300" height = "120"  />
<img src="http://www.aliacp.cn/wp-content/uploads/2017/06/b.png" width = "300" height = "120" />

**Comment by hirokokijima** [comment]
The same thing is happening here in Japanese characters, too.
It does not happen when the answer is provided only in alphabets.
Also it works fine with Japanese characters when using 4.x, but not in 5.x.
