### ISSUE TITLE
Not showing decimals in points

### ISSUE THREAD

**Issue by Testbusters** [QuizandSurveyMaster/quiz_master_next#559]
## General description
Points are integer instead of floats. Decimals are allowed in the creation of the quiz, and are shown in the result page, but don't work in the user dashboard and in the leaderboard.

## Expected behavior
Decimals points are displayed everywhere

## Actual behavior
Decimals only shown in the result page

## Steps to reproduce the behavior
Set a quiz on points evaluation, use decimals in the points of the answers, check leaderboard and user dashboard.

**Comment by fpcorso** [comment]
Hey @Testbusters 

Hmmm.... let me do some testing to see what's going on here.

**Comment by Testbusters** [comment]
Hi @fpcorso! 
Any update on this bug?

I saw other people opened the same issue (like [this](https://github.com/fpcorso/quiz_master_next/issues/640)).

This is quite important for us (and I believe for other users), because we're using quizzes based on points.

Thank you very much for your work!

**Comment by Testbusters** [comment]
Hi @fpcorso !
I'm sorry to bother you, but this is a very important feature for us, could you give me any update?

Thank you :)

**Comment by zubairraeen** [comment]
Hello,
I have tested this issue with the latest version of QSM, and it is now resolved and functioning correctly. Therefore, I am closing this task.

Thank you!
