### ISSUE TITLE
Stop videos when advancing to the page after video

### ISSUE THREAD

**Issue by KNC-KK** [QuizandSurveyMaster/quiz_master_next#567]
Thanks for giving us an opening on GitHub for these reports, Frank. That said, following is the issue/bug I've come across.

##Installation specifics:

- Wordpress 4.8.1,
- Theme - Photolite 1.2.6.1470367106 with modifications (have run tests w/default WP TwentyX themes to the same effect, FYI)
- QSM 5.0.6,
- PHP 5.4.19, 

## General description
I've embedded a video into my quiz, which allows a single question at a time. The embed itself works fine (regardless of whether the embed is HTML, shortcode based, from YouTube, Wistia, or a file directly uploaded into Wordpress), _but_ this happens when I test the quiz: I'll get the video question, play it halfway, and I can still proceed to the next question with the video running. This wouldn't be a problem, except the audio keeps playing after the AJAX (I assume) code loads the next question; it doesn't throw any command to stop the stream.

## Expected behavior
Needless to say, I thought the "next" or "previous" buttons would kill the video's audio stream when advancing to the actual question.

## Actual behavior
If I test the quiz - in actuality via a page with the quiz' shortcode, not the test function built into QSM - I'll put my name/email/info in and click "next." Question 1 shows up, and it's the video. I'll play the video halfway through, click "next" again, and get Question 2. Though Q2 is now up, and the video is no longer visible, I can still hear the video's audio continuing to play. Same volume, no break.

## Steps to reproduce the behavior
This can be replicated by taking a clean version of Wordpress, installing QSM on it, uploading a video into said new WordPress installation, and embedding the video into the "Question and Answers" text area of the "Add New Question" management area of QSM. Then, create a second dummy question (so you can advance to another question rather than the end of the quiz) and set the "How many questions per page would you like? (Leave 0 for all questions on one page)" setting to "1" in the options list. Create a new temporary page and dump the [qsm quiz=1] shortcode in a text field. Save the page, then view it. Enter the quiz, play the video, and before the video is done, advance to the second question. The audio should still be playing after advancing to the next question.

Thanks for looking into this.

-KK

**Comment by fpcorso** [comment]
Hey @KNC-KK 

Thanks for posting this. I actually had never considered this before. This will be a challenging one to solve. I'll look into this to see what I can come up with.

**Comment by KNC-KK** [comment]
Thanks for looking into it.

I'm not a coder, but I take it that it's not as simple as targeting the video with a JavaScript stop function run each click of next/previous (due to the different video players that may be used); correct?

I'm just throwing this out there, but - if this is the case - I wonder if it would be simpler to have a video-only question option. You'd be able to limit the series of services (e.g., Wordpress embedded, YouTube, and Vimeo) thus keeping the associated code upon each click to a minimum.

-KK
