### ISSUE TITLE
Special characters in quiz/survey name causing an issue with email subject lines

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#570]
## General description
A user just sent in a ticket stating that she has an apostrophe in the quiz name and it is causing "the email subject line put in the yucky html".

## Steps to reproduce the behavior
I have not verified or tested this behavior yet. Looking into it...

**Comment by zubairraeen** [comment]
Hello,
I have tested this issue with the latest version of QSM, and it is now resolved and functioning correctly. Therefore, I am closing this task.

Thank you!
