### ISSUE TITLE
Dynamically add class for correct/incorrect answers not working

### ISSUE THREAD

**Issue by sriordan9** [QuizandSurveyMaster/quiz_master_next#634]
## General description
There may be a bug for the option to dynamically add class for correct/incorrect answers. Did not add a class when option was checked.

## Feature request
User would like to be able to use css to color correct/incorrect answers as they are clicked during quiz.  User email: "i need to assign css to correct and wrong answers... I want when the correct answer clicked to turn green or turn red if the answer is wrong"

**Comment by sriordan9** [comment]
Another user has requested a fix for this

**Comment by sriordan9** [comment]
Another user has requested that this bug be resolved

**Comment by zubairraeen** [comment]
Hello,
I have tested this issue with the latest version of QSM, and it is now resolved and functioning correctly. Therefore, I am closing this task.

Thank you!
