### ISSUE TITLE
Timer restarts when page is scrolled

### ISSUE THREAD

**Issue by fahaadsheikh** [QuizandSurveyMaster/quiz_master_next#642]
Please provide the following information when creating your issues:

## General description
The timer for the quiz restarts when within a quiz I scroll down.

## Expected behavior
The timer for the quiz should not restart.

## Actual behavior
When I scroll the timer restarts with no error on the console.

**Comment by fahaadsheikh** [comment]
http://take.ms/qafz8

**Comment by fahaadsheikh** [comment]
Further debugging:

Problem Occurs only for window size above 1000px.
Problem does not occur with default Wordpress themes.

**Comment by fahaadsheikh** [comment]
If someone is using bridge theme. There was a conflict in the default js file that comes along bridge theme.

Here's the code that I added to fix it:

```php
function` resolve_timer_reset_issue_bridge() {
    
    if (is_singular( 'quiz' )) {
      wp_dequeue_script( 'default' );
    }
}
add_action( 'wp_print_scripts', 'resolve_timer_reset_issue_bridge' );
```

**Comment by fpcorso** [comment]
Hey @fahaadsheikh 

Hmmm... I have never seen this before with this plugin. Do you happen to have a link to the default .js file or could you paste it here if it is small so that I can see what may be causing this behavior?

**Comment by fahaadsheikh** [comment]
@fpcorso I can share the url where you can see the problem with the file being loaded I just need somewhere private I can send you the link. An email mayb?

**Comment by fpcorso** [comment]
Hey @fahaadsheikh, you can use our contact us page https://quizandsurveymaster.com/contact-us/ and just mention this conversation so it gets to me.

**Comment by fahaadsheikh** [comment]
@fpcorso I've emailed you a long time ago. Haven't heard back yet.

**Comment by fpcorso** [comment]
Hey @fahaadsheikh Thank you for sending in the email. When I go to the link you provided, I cannot get the timer to restart when I scroll on the page. I tried in both Edge and Chrome.

Are you still experiencing this issue? If so, which browser are you using?
