### ISSUE TITLE
Allow more than one condition per question with logic addon

### ISSUE THREAD

**Issue by sriordan9** [QuizandSurveyMaster/quiz_master_next#655]
## General description
User would like option to place more than one condition on a single question while using the logic add-on. Example: on question 1 if user chooses answer 1 then next question shown will be question 2. However if user chooses answer 2 for question 1 then the next question will be question 3.

## Feature request
User email:  "I have a question # 1, the user can answer by \"Yes\" or \"No\". If he answers \"Yes\" I want him to be redirected to question #2 If he answers \"No\" I want him to be redirected to question #3 So I added two rules in the logic tab : A : When this happens : Q1 is equal to yes - Do this : Show Q2 B : When this happens : Q1 is equal to no - Do this : Show Q3 When I preview the quiz, if I select \"Yes\" is works well, but if I select \"No\", nothing appears, Q3 doesn\'t show."

**Comment by fpcorso** [comment]
@sriordan9 For the user's email, would this be set up as two rules instead of two conditions on the same rule? Does it work that way?

**Comment by sriordan9** [comment]
I've tried setting it up as two separate rules, but it doesn't work that way either.
