### ISSUE TITLE
Retake quiz button on results page

### ISSUE THREAD

**Issue by sriordan9** [QuizandSurveyMaster/quiz_master_next#661]
## General description
User would like to have an optional button at quiz end to retake the quiz (that reloads the quiz only, not the entire page).

## Feature request
User Email: "an option to add a button after you get the result of a quiz to play the complete quiz again.

...added a button myself...which reloads the whole page but it would be better to just get a reload of the quiz. Also I can imagine that the reload button doesn't have to be in the result page itself but could also appear under the result."

**Comment by vikasprogrammer** [comment]
We have got some other people requesting it as well.
