### ISSUE TITLE
Extend "dynamically add classes" & "numbering questions" options to admin results page

### ISSUE THREAD

**Issue by sriordan9** [QuizandSurveyMaster/quiz_master_next#663]
## General description
User would like to not only see options to "dynamically add classes" and "number questions" within the quiz but also in the admin results.

User email: "Numbers 1-10 are correctly displayed on the Quiz page and on the Results page after the user has submitted their answers. However, they are NOT displayed in the Admin Results page... Also, I checked the box to add a CSS class for a correct and incorrect answer... Again, these colours are added to the Quiz and Results page after the user has submitted their answers, but NOT in the Admin Results page."

**Comment by fpcorso** [comment]
Hmmm.... @sriordan9 I wonder if we should split this issue into two separate issues. My thinking is that we may implement one of these before the other and need a way to close one.

**Comment by sriordan9** [comment]
Issues have been split, see #734 for other issue.
