### ISSUE TITLE
Random symbols appears close to submit

### ISSUE THREAD

**Issue by Testbusters** [QuizandSurveyMaster/quiz_master_next#679]
I still haven't figured out how, but sometimes some "wild chars" appears close to the submit button.

## General description
One picture is worth a thousand words: https://imgur.com/8p5pwnR

## Expected behavior
I would expect no random chars to appear.

## Actual behavior
"wild chars" appears

## Steps to reproduce the behavior
Sometimes creating and deleting questions is enough to reproduce the behaviour, sometimes importing questions triggers it, sometimes also just creating a quiz with one question is enough to generate the problem.

**Comment by fpcorso** [comment]
Wow @Testbusters. I have not seen those before in QSM. I will definitely have to try to replicate this and see what I can find. Thanks for reporting!

**Comment by Testbusters** [comment]
Hi @fpcorso! Any update? I still have the problem:

![image](https://user-images.githubusercontent.com/29711996/50086793-72bfbc80-01fe-11e9-86e7-2d41b22b297a.png)
