### ISSUE TITLE
Display Reporting and Analysis addon stats on front end of sites

### ISSUE THREAD

**Issue by sriordan9** [QuizandSurveyMaster/quiz_master_next#692]
## General description
User would like to have the option to show quiz statistics on the front end through shortcodes for the Reporting and Analysis addon.

## Feature request
User email: "Does the reporting addon include shortcodes for displaying results on the front-end in a page/post etc?"

**Comment by sriordan9** [comment]
Another request has been made for this feature. User email: "Can I integrate the Reporting and Analysis Add On [with the Advanced Leaderboard Addon] to display the results in an chart? So that the user can see his answer and a chart with de answers of all users who took the survey before him. "

**Comment by sriordan9** [comment]
Another request has been made for this feature.

User email: "I'd like to display the cumulative results in a graph, right after the user has given his answer... is there a way to embed these graphs in the current page, other than downloading the picture file and incorporating it in my website?"

**Comment by vikasprogrammer** [comment]
Will release this next week. Sorry for such a long wait time.
