### ISSUE TITLE
Javascript shown as text in archives page

### ISSUE THREAD

**Issue by sriordan9** [QuizandSurveyMaster/quiz_master_next#693]
## General description
When viewing the archives page, portions of the Javascript (such as if statements) are displayed as text beneath the quiz title. 

Example: 
(window.qmn_quiz_data === undefined) { window.qmn_quiz_data = new Object(); }

**Comment by zubairraeen** [comment]
Hello,
I have tested this issue with the latest version of QSM, and it is now resolved and functioning correctly. Therefore, I am closing this task.

Thank you!
