### ISSUE TITLE
Emails do not send on certain hosts as HTML

### ISSUE THREAD

**Issue by fpcorso** [QuizandSurveyMaster/quiz_master_next#695]
## General description
Certain hosts/servers will not send HTML emails from the WordPress installation. Our plugin, currently, only sends HTML emails and not plain text. This causes these sites to not send emails.

## Expected behavior
The plugin should be able to send both HTML and plain text emails.

## Actual behavior
The plugin only sends HTML emails which causes it to not work on certain tech stacks.

**Comment by zubairraeen** [comment]
Hello,
I have tested this issue with the latest version of QSM, and it is now resolved and functioning correctly. Therefore, I am closing this task.

Thank you!
