### ISSUE TITLE
"Time has expired" message when using timer option 

### ISSUE THREAD

**Issue by sriordan9** [QuizandSurveyMaster/quiz_master_next#716]
## General description
User would like for a message "Time has expired" to be displayed when the quiz taker runs out of time.

## Feature request
Possibly make the message include "please navigate to the quiz end and submit" as the quiz doesn't currently auto submit when the time expires.

**Comment by adrienjolion** [comment]
And if we also added the option of switching to a certain color beyond a certain time spent on the timer ?
