### ISSUE TITLE
Option to disable contact field auto fill 

### ISSUE THREAD

**Issue by sriordan9** [QuizandSurveyMaster/quiz_master_next#718]
## General description
User would like to have an option to disable the automatic population of contact fields such as the name of a quiz taker.

## Feature request
User email: "Before a customer takes the test, they fill in the QSM contact fields of which the first one is for them to enter their first and last name... if the customer logs off before taking the test, and then logs back on to take the test, the customer's login id is automatically entered in the QSM contact name field. Then every once in a while, a customer doesn't realize that the name field contains their login id instead of their first and last name in it. So when they print the certificate, it has their login id where their name should be on it. "

**Comment by vikasprogrammer** [comment]
Fixed in v6.3.1 https://github.com/QuizandSurveyMaster/quiz_master_next/releases/tag/6.3.1
