### ISSUE TITLE
Plugin conflict with "Forget About Shortcode Buttons" v2.1.1

### ISSUE THREAD

**Issue by sriordan9** [QuizandSurveyMaster/quiz_master_next#726]
## General description
This plugin prevents our "add media" button from responding when clicked. Nothing happens.  

User email: "When Editing a question, pressing the Add Media button does absolutely nothing. I expect it to open the Media Library, but it does nothing at all."

**Comment by vikasprogrammer** [comment]
No problem found during testing. Closing
