### ISSUE TITLE
Radio buttons & dropdown list for the Contact form at the end

### ISSUE THREAD

**Issue by YitongM** [QuizandSurveyMaster/quiz_master_next#755]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.0.3
QSM Version: Version 6.1.2
Browser: 

## Feature request
In the contact form at the beginning/end of the quiz, please add radio buttons and/or dropdown list so we can ask for "Mr. Mrs.". Thank you!

**Comment by fpcorso** [comment]
Hey @Yistine 

Thanks for adding these feature requests! I think both of these sound great. For project management and timeline purposes, can you separate these out into two separate GitHub issues?

**Comment by Yistine** [comment]
> Hey @Yistine
> 
> Thanks for adding these feature requests! I think both of these sound great. For project management and timeline purposes, can you separate these out into two separate GitHub issues?

Thank you for your reply, it's done. :)
