### ISSUE TITLE
Modify 1 quiz but all quizzes changed to the same

### ISSUE THREAD

**Issue by YitongM** [QuizandSurveyMaster/quiz_master_next#758]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.0.3
QSM Version: Version 6.2.0
Browser:

## General description
I'm sorry to bother you again. But I ran into a bug as well. I have 3 quizzes. The last two was duplicated from the 1st one. When I came into 1 of them to modify every questions, somehow all my quizzes became the same questions. And when I tried to add a word in one question for testing, all quizzes added that word on that same question. Is this the normal behavior? Thank you in advance for your help! Your plugin is still great!

## Expected behavior
Duplicated quiz should be independant on the original one.

## Actual behavior
I modify 1 quiz, all quizzes changed to the same.

## Steps to reproduce the behavior
- Create a quiz with some questions
- Duplicate this quiz
- Modify the 2nd quiz
- Check the 1st quiz if it changed.

**Comment by vikasprogrammer** [comment]
Related issue - https://wordpress.org/support/topic/does-not-work-properly-23/

**Comment by vikasprogrammer** [comment]
Fixed in https://github.com/QuizandSurveyMaster/quiz_master_next/commit/3790039745d3265d492095333e3e0ea7b5d5b35d
