### ISSUE TITLE
Quiz show empty page with logic add-on

### ISSUE THREAD

**Issue by telmott** [QuizandSurveyMaster/quiz_master_next#760]
## Site Info
WordPress Version: 5.0.2
QSM Version: 6.0.4
QSM - Logic: 1.0.1
Browser: chrome 71.0.3578.98

## General description
While filling the quiz, if you get to a page in which the questions have been hidden by the logic plugin the page is shown empty.

## Expected behavior
When you press the next button, it should skip pages with hidden questions.

## Actual behavior
When you press the next button, the page is shown empty even if the questions are hidden.

## Steps to reproduce the behavior
Create a paged quiz with one question per page, hide some questions with the login add-on and then fill out the quiz.

If this is the normal behavior, and if there's another way to achieve this, please let me know what am I doing wrong.

If it´s a bug I can submit a PR with a fix if you´re interested to see my solution.
Thanks.

**Comment by vikasprogrammer** [comment]
Please submit the PR. However, logic addon is repo is hosted on bitbucket. Can you send your solution to vikas@expresstech.io?

**Comment by vikasprogrammer** [comment]
Closed via PR https://github.com/QuizandSurveyMaster/quiz_master_next/pull/787
