### ISSUE TITLE
Get Quiz and Survey Data Using Wordpress API

### ISSUE THREAD

**Issue by vkiranmaniya** [QuizandSurveyMaster/quiz_master_next#769]
## Site Info
WordPress Version: 5.1.0
QSM Version: 6.0.3
Browser: Chrome

## Feature request
The Plugin Works fine in Website. But I Need the RestAPI to show data in Mobile. I didn't find any documentation for it. Is it possible to get Quiz and Survey Data in JSON/XML form via Rest API? Quiz and Survey Plugin Should have the capability to serve the Data in Standard Data Transport Format like JSON or XML. Wordpress Post Supports it.

**Comment by vikasprogrammer** [comment]
```
/qsm/list_quiz
/qsm/list_results/<quiz_id>
```
Implemented in QSM v6.3.5

**Comment by ta712** [comment]
@vikasprogrammer 

How can i fetch single test  quiz page

**Comment by zubairraeen** [comment]
We have released our new REST API with QSM 9.0.0. For more information, please refer to this link: [QSM REST APIs](https://quizandsurveymaster.com/docs/developer/quiz-survey-master-api/#QSM_rest_APIs).
