### ISSUE TITLE
[Feature request] Can I add images to the answer choices?

### ISSUE THREAD

**Issue by akai1983** [QuizandSurveyMaster/quiz_master_next#770]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.0.4
QSM Version: 6.2.2 
Browser:  chrome latest

## General description

Can I add images to the answer choices ? 

## Feature request

Can I add images to the answer choices ?

**Comment by vikasprogrammer** [comment]
Yes, we have already enabled Rich Answers. Select Rich answers from dropdown and then you can add anything.
