### ISSUE TITLE
Preserve carriage returns/line feed in email results

### ISSUE THREAD

**Issue by CryBabyOne** [QuizandSurveyMaster/quiz_master_next#772]
Using a textform for example in a open essay or a list and adding text with carriage returns/line feeds  and when the results are sent with email it strips all carriage returns/line feeds and all text comes in one long row (oneliner).

For example:
**First sentence
Second sentence
Third sentence**

Comes out like:

**First sentence Second sentence Third sentence**

Feature request
I would like the email results keep the carriage returns/line feeds.

**Comment by vikasprogrammer** [comment]
Good idea, will include in next version.

**Comment by vikasprogrammer** [comment]
Can you pls provide the screenshot of the textform or the UI you are using with QSM? Our dev is not able to replicate this issue.

**Comment by vikasprogrammer** [comment]
Not able to replicate, closing it.
