### ISSUE TITLE
Add filter to results array 

### ISSUE THREAD

**Issue by mark-obrien** [QuizandSurveyMaster/quiz_master_next#785]
## Site Info
WordPress Version: 5.1.0
QSM Version: 6.0.3
Browser: Chrome

## Feature request
A client wants to allow any answer for long/short text questions to be correct. I would like to have a filter added to the `$results_array` so I can do that.

https://github.com/QuizandSurveyMaster/quiz_master_next/blob/master/php/classes/class-qmn-quiz-manager.php#L1053

**Comment by mark-obrien** [comment]
PR open - https://github.com/QuizandSurveyMaster/quiz_master_next/pull/786

**Comment by vikasprogrammer** [comment]
Thanks Mark, merged with `dev` branch for testing.
