### ISSUE TITLE
TOTAL_QUESTIONS variables doesn't seem to work

### ISSUE THREAD

**Issue by bitsnaps** [QuizandSurveyMaster/quiz_master_next#797]
## Site Info
WordPress Version: 5.2.4
QSM Version: 6.3.2
Browser: Chrome

## General description
The variable `%TOTAL_QUESTIONS%` doesn't seem to work.

## Expected behavior
Shows the total count of questions.

## Actual behavior
it just shows the raw string `%TOTAL_QUESTIONS%`.

## Steps to reproduce the behavior
Create a new quiz at the welcome text insert `%TOTAL_QUESTIONS%` and save the quiz.

**Comment by zubairraeen** [comment]
Hello,
I have tested this issue with the latest version of QSM, and it is now resolved and functioning correctly. Therefore, I am closing this task.

Thank you!
