### ISSUE TITLE
BUG - Image link in quiz don't have correct caracter, and i get a 404

### ISSUE THREAD

**Issue by Porkass** [QuizandSurveyMaster/quiz_master_next#809]
Hello,

Since few update (i don't know how many update of this plugin) images link don't work.

The name of image have special caracter x for image resolution and my nginx get a 404 error :
URL in my quiz : diaphragme-photo-1-1024×683-300×200.jpg
Correct url : diaphragme-photo-1-1024x683-300x200.jpg

This problem appear only in this plugin, all of my site work nice.

Have you any idea to resolve this issue ?

Here my site information :
WordPress Information

Version: 4.9.12
Language: fr_FR
Permalink Structure: /%postname%/
Active Theme: Donovan 1.4.3
Parent Theme: Donovan 1.4.3
Debug Mode: Disabled
Memory Limit: 40M

PHP : 7.3.12
MySQL : 5.5.5
Webserver : nginx/1.16.1
QSM Information

Initial Version : 6.3.3
Current Version : 6.3.6

I have this in my wp-config.php :
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

My OS is a CentOS 7 up to date, with my local in fr_FR.utf8

I hope you can help me !

Best Regards,
Fabien

**Comment by Porkass** [comment]
Hello, 

Since few update (i don't know how many update of this plugin) images link don't work.

The name of image have special caracter x for image resolution and my nginx get a 404 error : 
URL in my quiz : diaphragme-photo-1-1024×683-300×200.jpg
Correct url : diaphragme-photo-1-1024x683-300x200.jpg

This problem appear only in this plugin, all of my site work nice.

Have you any idea to resolve this issue ?

Here my site information : 
WordPress Information

Version: 4.9.12
Language: fr_FR
Permalink Structure: /%postname%/
Active Theme: Donovan 1.4.3
Parent Theme: Donovan 1.4.3
Debug Mode: Disabled
Memory Limit: 40M

PHP : 7.3.12
MySQL : 5.5.5
Webserver : nginx/1.16.1
QSM Information

Initial Version : 6.3.3
Current Version : 6.3.6

I have this in my wp-config.php : 
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

My OS is a CentOS 7 up to date, with my local in fr_FR.utf8

I hope you can help me !

Best Regards,
Fabien

**Comment by vikasprogrammer** [comment]
Please raise a support request at support.quizandsurveymaster.com, we will help you there.
