### ISSUE TITLE
Special capabilities

### ISSUE THREAD

**Issue by Cocoslocos** [QuizandSurveyMaster/quiz_master_next#810]
## General description
I would like different capabilities to be added to the plugin, that is, that users can create their surveys and not edit that of others.

## Feature request
Different capacities can be added, for example:
User: You can create, edit, publish and delete your surveys, but not edit those of other users.
Administrator: you can create, edit, publish and delete all surveys.

**Comment by vikasprogrammer** [comment]
We need to introduce capabilities in QSM for this to happen. We will put this on our roadmap and provide timelines soon.

**Comment by etvarun** [comment]
We have added the following functionality:

Users on Author level can create and edit its own quiz only.
Users on Administrator level can edit all quizzes.
