### ISSUE TITLE
Timer for question

### ISSUE THREAD

**Issue by admin19831983** [QuizandSurveyMaster/quiz_master_next#823]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.3.2
QSM Version: 6.3.4
Browser: Chrome

## General description
it woutld be great if there is a timer for questions 

Link to quiz or screenshot (if relevant):

**Comment by kriti-support** [comment]
Hi,

Hope you are doing well.

I will forward your feature request regarding 'the implementation of timer for quiz questions' to the development team. We will try to release it in the future updates.

Kind regards,
Kriti
