### ISSUE TITLE
Email addresses appaering without '@'

### ISSUE THREAD

**Issue by Subin98** [QuizandSurveyMaster/quiz_master_next#831]
## Site Info
WordPress Version: 5.3.2
QSM Version: 6.4.1
Browser: chrome

## General description
There is an issue with the latest edition of this plugin, as the email addresses  that we enter on a contact fields during a quiz  is stored on database without '@".
example:
 example@example.com
Appearing as exampleexample.com on result page.
## Expected behavior
so email address should be stored as it is collected from the user.

**Comment by vikasprogrammer** [comment]
Thanks for the report, we are aware of this issue and will release a fix by tomorrow.

**Comment by Subin98** [comment]
Could you please mention when can we fix as, i  am using this on one of my live site.

**Comment by vikasprogrammer** [comment]
Its pushed to WP repo now, please update your plugin.

**Comment by vikasprogrammer** [comment]
Solved in 6.4.2+
