### ISSUE TITLE
Some answers were not recorded.

### ISSUE THREAD

**Issue by qothrunnadaa** [QuizandSurveyMaster/quiz_master_next#841]
## Site Info
WordPress Version: 5.3.2
QSM Version: 6.2.0
Browser: Google Chrome

## General description
This bug I found since the update to the latest version and has not been resolved until now. Some answers were not recorded to the admin database, this problem often arises when there are a lot of questions and contain a lot of text

Link to quiz: https://arabic.qothrunnadaa.com/soal-evaluasi-kelas-online/soal-evaluasi-23-level-1/

please do the questions by answering all the questions.

Later you see on the result page there is one problem that you are not working on so that your results are reduced
This is a screenshot of the results of my answer that was not recorded: http://prntscr.com/r4u38y

## Expected behavior
I hope all answers are recorded well

## Feature request
Please add the "short by name or date or class" feature to the admin dashboard to make it easier to sort questions

**Comment by kriti-support** [comment]
Hi there,
Please make sure that there are no empty blank spaces at the end of the answers. Sometimes empty blank spaces at the end of the answers doesn't allows the quiz to record the answers. Please let me know if this solves the problem or not.

Regards,
Kriti
