### ISSUE TITLE
Request For Result Page Redirect Feature 

### ISSUE THREAD

**Issue by dindar123** [QuizandSurveyMaster/quiz_master_next#843]
I want to redirect my quiz takers to the unique result page without creating separate results pages. 

Right now I am manually creating lots of separate pages and set redirect url in qsm results. I have found quiz on [this site](https://illnessquiz.com/sociopath-test/), which is redirecting quiz takers automatically to result page. so please add this feature in the next update.

**Comment by vikasprogrammer** [comment]
Thanks, will check this. @etvarun
