### ISSUE TITLE
Scroll Up for top

### ISSUE THREAD

**Issue by florent03** [QuizandSurveyMaster/quiz_master_next#848]
https://longtimelabel.com
WordPress 5.3.2 avec le thème Divi.
QSM Version 6.4.4
Firefox 73.0.1

When changing pages or sections in the form, users are directed to the bottom of the page. They must systematically scroll back to the top of the page, which greatly affects the readability of the form.

Is there an option to fix this problem or is it necessary to intervene on the code?

https://longtimelabel.com/annexe_sectorielle_wm_retailer/

**Comment by usman297** [comment]
Our developer team already working on it , We will let you know ASAP
