### ISSUE TITLE
Bad html output with Rich Answers

### ISSUE THREAD

**Issue by MrMasterMoe** [QuizandSurveyMaster/quiz_master_next#849]
QSM Version: 6.4.4
Browser: NA

## General description

These two lines in guestion-types.php:

				$question_display .= "<div class='qmn_mc_answer_wrap' id='question".$id."-".esc_attr($answer[0])."'>";
        $question_display .= "<input type='radio' class='qmn_quiz_radio' name='question".$id."' id='question".$id."_".$mlw_answer_total."' value='".htmlentities(esc_attr($answer[0]))."' /> <label for='question".$id."_".$mlw_answer_total."'>".htmlspecialchars_decode($answer[0], ENT_QUOTES)."</label>";

output the full html of the option in the ID of wrapper div and in the value of the option:

<div class='qmn_mc_answer_wrap' id='question2-&lt;img class=&quot;alignnone size-full ff-image-27679&quot; src=&quot;https://favorflav.local/images/Nacht-van-de-Wijn-.jpg&quot; alt=&quot;&quot; width=&quot;1200&quot; height=&quot;628&quot; /&gt;&lt;br /&gt;&lt;span style=&quot;color: #ff6600;&quot;&gt;&lt;strong&gt;Lets add some extra stuff here&lt;/strong&gt;&lt;/span&gt;'>

<input type='radio' class='qmn_quiz_radio' name='question2' id='question2_1' value='&amp;lt;img class=&amp;quot;alignnone size-full ff-image-27679&amp;quot; src=&amp;quot;https://favorflav.local/images/Nacht-van-de-Wijn-.jpg&amp;quot; alt=&amp;quot;&amp;quot; width=&amp;quot;1200&amp;quot; height=&amp;quot;628&amp;quot; /&amp;gt;&amp;lt;br /&amp;gt;&amp;lt;span style=&amp;quot;color: #ff6600;&amp;quot;&amp;gt;&amp;lt;strong&amp;gt;Lets add some extra stuff here&amp;lt;/strong&amp;gt;&amp;lt;/span&amp;gt;'>

![quiz_master_bug](https://user-images.githubusercontent.com/61826713/75972454-c128ac00-5ed3-11ea-8bbf-af4ef930e3bd.jpg)

Cheers!

**Comment by etvarun** [comment]
@MrMasterMoe This has been fixed in latest release.

Thank you.
