### ISSUE TITLE
"Polar" type questions have points wrongly reported (always 0)

### ISSUE THREAD

**Issue by nunomorgadinho** [QuizandSurveyMaster/quiz_master_next#850]
WordPress Version: 5.3.2
QSM Version: 6.4.4
Browser: Google Chrome 80.0.3987.122 (Official Build) (64-bit)

## General description
When using a question of type "Polar" the points in the results array comes 0.

## Expected behavior
I was expecting the points to be reported correctly like for other question types.

## Actual behavior
Points are always 0.

## Steps to reproduce the behavior
1. Create a quiz with a question of type "Polar".
2. Create 3 answers for that question: 0% - 0 points, 50%- 5 points, 100% - 10 points.
3. Take the Quiz and check your points.

**Comment by etvarun** [comment]
@nunomorgadinho Thank you for sharing this. We have recored this bug and will try to provide a fix soon.

**Comment by kriti-support** [comment]
Hi,

We have fixed this bug in the Qsm version 6.4.6. Thanks for being with us. 

Kind regards, 
Kriti 
Qsm Support
