### ISSUE TITLE
Experiment capability Featurerequest

### ISSUE THREAD

**Issue by phpchess** [QuizandSurveyMaster/quiz_master_next#854]
## Site Info
WordPress Version: 5.3.2
QSM Version: 6.2
Browser: Chrome

## General description
permit pages to be created as a section (think 3 pages and 1 question, page1 introduces a scenario, page 2 gives an outcome, page three asks a question (rate out of 5 for example). Sections should be either sequential or randomized. This extension would permit the creation of experiments, which should be a new category of surveys, and maybe worth money?

## Feature request
In priciple I simply would like a randomly selected set of questions on different pages, and pages to be groupable and these groups to be randomized. You have all other functionality. An experiment as an intorducory set of pages and maybe even a question (age, gender, ....). In experiments you then have sections. Each section can have one or more introductory pages, and one or more questions. It would be great to be able to randomise the sections to enable the set-up pages and questions to stay together. Experimenters have to fight with rubbish like php & mysql as well as spss, Open Sesame and other horror tools. This would make life alot easier!

**Comment by etvarun** [comment]
@phpchess We have recorded this request and will consider it in our future releases.

**Comment by vikasprogrammer** [comment]
This will take a lot of work and looks like a specific use case. If more users ask for this request we may consider in future or if you want to get this done right away use our services partner - https://justhyre.com/get-a-quote/

**Comment by phpchess** [comment]
thanks. I ended up writing my own bespoke code in a couple of days in a hack (php + mysql)
I still think there is a bigger market here especially in academia. Thanks again for considering.
