### ISSUE TITLE
Error Code 0001

### ISSUE THREAD

**Issue by Podter** [QuizandSurveyMaster/quiz_master_next#873]
## Site Info
WordPress Version: 5.4
QSM Version: 6.4.5
Browser: Microsoft Edge Chromium on Windows

## General description
So I'm new on this plugin and after I installed it and I can't wait to create new quiz but after that I given the quiz name and click Create. It doesn't create the quiz and show the 0001 Error code!

Screenshot : 
![image](https://user-images.githubusercontent.com/48936015/78454038-b70af080-76bf-11ea-9fcb-5e3cdbe20961.png)

## Postscript
I'm tried to change the version of the WordPress but still same problem!

**Comment by etvarun** [comment]
Hi @Podter, looks like there is some issue with your setup. 
[Please create a ticket at our support forum](https://support.quizandsurveymaster.com/support/product/qsm-pro-support/) and our team will help you resolve this.
