### ISSUE TITLE
Quotes in custom CSS

### ISSUE THREAD

**Issue by cedrick-f** [QuizandSurveyMaster/quiz_master_next#874]
Hi

## Site Info
WordPress Version: 4.9.13
QSM Version: 6.4.5
Browser: Firefox

## General description
I would like to add some texte before question number with custom css 👍 

.mlw_qmn_question_number::before {
     content: "Question " !important;
}

But the quotation mark is not taken into account, as can be seen with Firefox inspector :
![image](https://user-images.githubusercontent.com/11462584/78587225-ec891880-783c-11ea-8355-39eb610ec351.png)

Thanks for your help

**Comment by etvarun** [comment]
Hi @cedrick-f,

We have fixed this issue and will include the fix in our next release.

Meanwhile you can manually download the code from our dev branch by using following link

https://github.com/QuizandSurveyMaster/quiz_master_next/archive/dev.zip

**Comment by kriti-support** [comment]
Hi,

We have resolved the bug in the latest plugin update, please update and let us know if you face any issue. 

Regards, 
Kriti

**Comment by cedrick-f** [comment]
Hi
It works parfectly now. Thanks !

Cédrick
