### ISSUE TITLE
Bug On new Update

### ISSUE THREAD

**Issue by thesagor** [QuizandSurveyMaster/quiz_master_next#878]
wp-content/plugins/quiz-master-next/js/qsm-quiz.js

Bug is here. Result page not showing

**Comment by vikasprogrammer** [comment]
we released a new update yesterday (6.4.7), that should fix this bug. let me know if it doesn't.

**Comment by thesagor** [comment]
auto responding not working

**Comment by usman297** [comment]
Hello, 
Can you explain the issue with more details, then our development team will look into it.

**Comment by thesagor** [comment]
when i use auto responding api then it not working as working before. Thank you

**Comment by usman297** [comment]
Hello, 
Please clear one thing, what is auto responding api?
