### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by diogenesc** [QuizandSurveyMaster/quiz_master_next#880]
Title: Javascript error detected by QSM Plugin
Message: Uncaught TypeError: $ is not a function
Filename: http://maia.seusite.xyz/wp-content/plugins/themetonaddon/js/elements.min.js?ver=5.3.2:1:20019
Stack: TypeError: $ is not a function
    at http://maia.seusite.xyz/wp-content/plugins/themetonaddon/js/elements.min.js?ver=5.3.2:1:20019
Page url: http://maia.seusite.xyz/quiz/pesquisa-de-satisfacao/
Refferer: http://maia.seusite.xyz/wp-admin/admin.php?page=mlw_quiz_options&quiz_id=1&tab=preview
User-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
Screen size: 1920×1080×24
Screen orientation: landscape-primary
Cookie enabled: true

**Comment by usman297** [comment]
We have recorded this issue. Our developer team will look into it ASAP.

**Comment by usman297** [comment]
Hello, 
Our Developer team checked, It seems like this issue is not from our plugin it is from themetonaddon plugin.You can contact that plugin author. If still you need our help , please let us know. :)
