### ISSUE TITLE
Script error.

### ISSUE THREAD

**Issue by nosubanime** [QuizandSurveyMaster/quiz_master_next#885]
Title: Javascript error detected by QSM Plugin
Message: Script error.
Filename: :0:0
Stack: 
Page url: https://nosubanime.altervista.org/quiz/otaku-quiz/
Refferer: https://nosubanime.altervista.org/wp-admin/admin.php?page=mlw_quiz_options&quiz_id=4&tab=preview
User-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 Edg/80.0.361.111
Screen size: 1746×982×24
Screen orientation: landscape-primary
Cookie enabled: true

**Comment by usman297** [comment]
Hello, We recorded this issue, our Engineering team will look into it ASAP
