### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression flags

### ISSUE THREAD

**Issue by olumide665** [QuizandSurveyMaster/quiz_master_next#886]
Title: Javascript error detected by QSM Plugin
Message: Uncaught SyntaxError: Invalid regular expression flags
Filename: https://eruditespot.com/wp-content/cache/minify/f8936.js:14:13302
Stack: SyntaxError: Invalid regular expression flags
Page url: https://eruditespot.com/quiz/economics/
Refferer: https://eruditespot.com/wp-admin/admin.php?page=quiz-master-next%2Fmlw_quizmaster2.php
User-agent: Mozilla/5.0 (Linux; Android 8.1.0; Infinix X606) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Mobile Safari/537.36
Screen size: 360×720×24
Screen orientation: portrait-primary
Cookie enabled: true

**Comment by usman297** [comment]
Hello, We recorded this issue, our Engineering team will look into it ASAP
