### ISSUE TITLE
unable to embed quizzes

### ISSUE THREAD

**Issue by hasanoca** [QuizandSurveyMaster/quiz_master_next#893]
site: https://www.bebekce.gen.tr
wordpress latest version
QSM latest free version

I can’t embed the quizzes. I get the embedding code, paste it in a post (I even tried pasting it as a short code) then publish. The post displays the quiz as a whole. However, the submit button doesn’t work (though it seems clickable) and there is a “next” button beside it which does nothing. Therefore I can’t publish the quizzes as new posts. As I can’t categorize them, I have to add their links manually. Here is an example post for demonstration purposes: https://www.bebekce.gen.tr/2020/04/16/demo/

**Comment by usman297** [comment]
Hello,

We recorded this issue. Our Engineering team will look into it ASAP

**Comment by usman297** [comment]
Our Engineering Team checked Website.There are 3 issue in Jquery so you have to fix this issues after that quiz will work properly, Please find the attachment
![Annotation 2020-04-16 171319](https://user-images.githubusercontent.com/63340953/79458065-b56bf180-800a-11ea-84d3-254ab7410650.png)
