### ISSUE TITLE
New timer also for single questions in a quiz available?

### ISSUE THREAD

**Issue by admin19831983** [QuizandSurveyMaster/quiz_master_next#904]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.4
QSM Version: _6.4.8
Browser: chrome

## General description

i have a quiz with 65 questions. is it still not possible to use the timer for a single question?

Link to quiz or screenshot (if relevant): 

## Expected behavior
If you are reporting a bug, please describe what you are expecting the plugin to do. If this is a feature request, delete this section.

## Actual behavior
If you are reporting a bug, please describe what you are experiencing. If this is a feature request, delete this section.

## Steps to reproduce the behavior
If you are reporting a bug, describe the exact steps you are taking that results in the behavior described above. If this is a feature request, delete this section.

## Feature request
If you are reporting a bug, delete this section. If you are requesting a feature, please explain what you would like to have in the plugin. Please include examples of other systems/software that may have similar features as well as the exact way you would use this feature.

**Comment by usman297** [comment]
Hello,

We recorded this issue. Our Engineering team will look into it ASAP

**Comment by usman297** [comment]
Hello,
We recorded your query. We will keep you posted on future developments.

**Comment by usman297** [comment]
We will be releasing a new addon - Advance timer this week which allows you to start the timer on a particular page, so you can push the 1 question for which you need a timer to last page and start the timer then, that's all is currently possible. But you still need this custom functionality you can hire us as well. Please let us know if you need more help :)

**Comment by admin19831983** [comment]
Yes i want the help of your company, how does it work?

what i want if possible is the first 25 questions the customer have 8 seconde to answer the question

**Comment by usman297** [comment]
Hello,
Hope you are having a great day.If you like, I can forward this as the feature request to the development team and they will try to implement it in future updates. But if you still need this custom functionality you can hire us. 
You can also contact our development team at https://justhyre.com/get-a-quote/ , if you want to get it done as custom requirement on urgent basis.

**Comment by vikasprogrammer** [comment]
Just to add on what Usman has mentioned. We can do the "what i want if possible is the first 25 questions the customer have 8 seconde to answer the question", its certainly possible. Please write us on the link provided above and we will get back to you with quick quote.
