### ISSUE TITLE
hard to find out the wrong answers on result pages

### ISSUE THREAD

**Issue by hasanoca** [QuizandSurveyMaster/quiz_master_next#912]
www.bebekce.gen.tr
wordpress latest
QSM latest

Even I find it very hard to find out the mistakes that I have made on a quiz. You need to develop something about this. Mostly the the user's answers and the correct answers look identical and I have to copy each on a notepad to clearly see the difference. You might underline the wrong answers or give them a red color or something like this.
Example page: https://www.bebekce.gen.tr/testler/past-simple-or-past-continuous-test-3-when-while/
Thanks in advance.

**Comment by usman297** [comment]
Hello,
Hope you are having a great day.If you like, I can forward this as the feature request to the development team and they will try to implement it in future updates. If you still need this custom functionality you can hire us. You can contact our development team at https://justhyre.com/get-a-quote/ , if you want to get it done as custom requirement on urgent basis.

**Comment by etvarun** [comment]
@hasanoca, Thanks for the suggestions. We are planning to build a feature around this issue. For the time being you can use the following CSS snippet to highlight incorrect answers.

> .qmn_user_incorrect_answer {
> color: red;
> }
