### ISSUE TITLE
Submit button doesn't work on Safari, on my iPhone. 404. /wp-content/plugins/quiz-master-next/js/progressbar.min.js.map

### ISSUE THREAD

**Issue by a4jp-com** [QuizandSurveyMaster/quiz_master_next#934]
**IF YOU DO NOT FOLLOW THIS TEMPLATE, YOUR ISSUE MAY BE CLOSED!!**

Please provide the following information when creating your issues:

## Site Info
WordPress Version: 5.4.1
QSM Version: v6.4.11
Browser: Safari on iPhone Xs Max

## General description
Submit button doesn't work on Safari, on my iPhone but works on Chrome on my PC.

Link to quiz or screenshot (if relevant): [https://agreatdream.com/quiz/eiken-5th-grade-sample-test/](https://agreatdream.com/quiz/eiken-5th-grade-sample-test/)

## Expected behavior
Submit button should work on iPhone it works on Windows Chrome.

## Actual behavior
The submit button doesn't click.

## Steps to reproduce the behavior
Install update. Old working tests stop working on iPhone, Safari.

**Comment by etvarun** [comment]
Hi @a4jp-com,

We have tested the given quiz url on iphone XS max, iphone 11 and iphone pro. We are able to submit the results in each device without any problem.

This could be a cache issue on your device so kindly check this again by clearing your cache.

Best Regards.
Varun
